Repository kubewharf/katalyst-core, pull requests merged in 2023-11, with the labels that each got.

#334 support to disable isolation when exceeding total capacities
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/util/metric/store_util.go
Labels: bug, workflow/need-review, workflow/merge-ready

#337 chore(generic): add kube-aggregator client
  cmd/base/context.go
  cmd/base/context_fake.go
  go.mod
  go.sum
  pkg/client/genericclient.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#339 feat(metaserver): add node cpu usage ratio metric
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/metaserver/agent/metric/malachite/types/system.go
Labels: enhancement, workflow/merge-ready

#335 [WIP]feat(kcmas):mock collector
  cmd/katalyst-metric/app/metric.go
  cmd/katalyst-metric/app/mode/collect.go
  cmd/katalyst-metric/app/options/mock.go
  cmd/katalyst-metric/app/options/options.go
  pkg/config/metric/metric_base.go
  pkg/config/metric/mock.go
  pkg/custom-metric/mock/mock_collector.go
  pkg/custom-metric/mock/mock_store.go
  pkg/custom-metric/mock/utils.go
  pkg/custom-metric/mock/utils_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#344 spd support baseline ratio
  go.mod
  go.sum
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/helper.go
  pkg/client/control/spd.go
  pkg/controller/spd/spd.go
  pkg/controller/spd/spd_baseline.go
  pkg/controller/spd/spd_baseline_test.go
  pkg/controller/spd/spd_test.go
  pkg/metaserver/spd/manager.go
  pkg/util/spd.go
  pkg/util/spd_baseline.go
  pkg/util/spd_baseline_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#343 performance(kcmas): lock optimize
  pkg/config/metric/store.go
  pkg/custom-metric/provider/provider_test.go
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/cache_test.go
  pkg/custom-metric/store/data/internal/internal.go
  pkg/custom-metric/store/local/local_store.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#342 optimize(metric): optimize calculation of counter rate
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
Labels: workflow/merge-ready

#346 fix(kcmas): deadlock
  pkg/custom-metric/store/data/internal/internal.go
Labels: bug, workflow/need-review, workflow/merge-ready

#345 enhancement(sysadvisor): export region reclaimable info as non-reclaim when dedicated_cores can not be co-located with reclaimed_cores
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
Labels: enhancement, workflow/merge-ready

#349 enhancement(kcmas): object index
  cmd/katalyst-metric/app/options/store.go
  pkg/config/metric/store.go
  pkg/custom-metric/provider/provider.go
  pkg/custom-metric/provider/provider_test.go
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/cache_test.go
  pkg/custom-metric/store/local/local_store.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#352 add more eviction messages about threshold and observed values
  pkg/agent/evictionmanager/eviction_resp_collector.go
Labels: workflow/need-review, workflow/merge-ready

#357 fix(kcmas): nil pointer
  pkg/custom-metric/store/data/cache.go
Labels: bug, workflow/need-review, workflow/merge-ready

#360 perf(kcmas): remove high frequency monitor
  pkg/custom-metric/store/data/cache.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#361 perf(kcmas): don't purge useless metric meta
  pkg/custom-metric/provider/provider_test.go
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/local/local_store.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#359 refine numa-aware memory headroom policy
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware_test.go
Labels: enhancement, workflow/merge-ready

#358 enhancement(sysadvisor): update region info atomically
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_dedicated.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/helper.go
Labels: enhancement, workflow/merge-ready

#363 fix bugs for creating isolation region multiple times
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
Labels: bug, workflow/need-review, workflow/merge-ready

#314 feat(reporter-plugin): support report rdma topology
  cmd/katalyst-agent/app/options/reporter/kubelet_plugin.go
  pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go
  pkg/config/agent/reporter/kubelet_plugin.go
  pkg/util/cnr.go
Labels: enhancement, workflow/need-review

#372 misc: fix meeting link
  README.md
Labels: chore

#373 adapt to the latest version of katalyst api
  go.mod
  go.sum
  pkg/controller/spd/spd_baseline_test.go
  pkg/controller/spd/spd_test.go
  pkg/util/vpa_test.go
Labels: documentation, workflow/need-review, workflow/merge-ready

#374 updating counterDelta func
  pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
Labels: workflow/merge-ready

#376 feat(qrm): support register handler after group started
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
Labels: workflow/need-review

#378 fix(spd): remove interface
  pkg/controller/spd/indicator-plugin/manager.go
  pkg/controller/spd/spd_indicator.go
  pkg/controller/spd/spd_test.go
Labels: style, workflow/merge-ready

#379 node updater support patch node status
  pkg/client/control/node.go
  pkg/client/control/node_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#380 fix unit test race in sockmem plugin
  pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux.go
  pkg/agent/qrm-plugins/memory/handlers/sockmem/sockmem_linux_test.go
Labels: test failure, workflow/merge-ready

#384 fix(sysadvisor): always set regionInfo
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_dedicated.go
  pkg/agent/sysadvisor/types/cpu.go
Labels: bug, workflow/need-review
