Repository kubewharf/katalyst-core, pull requests merged in 2023-08, with the labels that each got.

#129 enhancement(eviction): load eviction support dynamic threshold
  cmd/katalyst-agent/app/options/dynamic/adminqos/reclaimedresource/reclaimedresource_base.go
  pkg/agent/evictionmanager/eviction_resp_collector.go
  pkg/agent/evictionmanager/manager.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pod_pool_getter.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_metric.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
  pkg/agent/qrm-plugins/util/util.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/config/agent/dynamic/adminqos/reclaimedresource/reclaimedresource_base.go
  pkg/util/machine/cpu.go
Labels: enhancement, workflow/need-review

#175 fix bugs to trim container id in pod spec
  pkg/metaserver/agent/metric/malachite/client/client.go
  pkg/metaserver/agent/metric/malachite/client/client_pod.go
  pkg/metaserver/agent/metric/malachite/client/client_pod_test.go
  pkg/util/cgroup/common/path.go
Labels: bug, workflow/need-review, workflow/merge-ready

#176 store metric by pod-uid and container-name
  pkg/metaserver/agent/metric/malachite/client/client_pod.go
  pkg/metaserver/agent/metric/malachite/client/client_pod_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#179 enhancement(eviction): enabled advised threshold when reclaim enabled
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#178 fix unit test race in config manager
  pkg/metaserver/config/checkpoint.go
Labels: bug, workflow/need-review

#181 fix omit zero static pool
  pkg/agent/sysadvisor/types/helper.go
Labels: workflow/merge-ready

#182 fix(qrm): fix log msg in validateStaticPools
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/validator/validator_cpu_advisor.go
Labels: workflow/merge-ready

#180 add stability status of region
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/types/cpu.go
Labels: workflow/need-review

#183 add kcmas metric for region info
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/advisor.go
  pkg/agent/sysadvisor/types/cpu.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#184 enhancement(eviction): heartbeat in cpu pressure eviction plugin
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#186 fix(qrm): only one periodical handler get executed
  pkg/agent/utilcomponent/periodicalhandler/periodical_handler.go
  pkg/agent/utilcomponent/periodicalhandler/periodical_handler_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#187 fix cpu/mem plugins oom
  go.mod
  go.sum
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
Labels: bug, workflow/need-review

#188 feat(qrm): implement time monitor to monitor advisor lw recv status
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/util/consts.go
  pkg/util/timemonitor/time_monitor.go
  pkg/util/timemonitor/time_monitor_test.go
Labels: workflow/need-review

#189 kcc support priority and its allowed selector key list
  go.mod
  go.sum
  pkg/consts/kcc.go
  pkg/controller/kcc/cnc_test.go
  pkg/controller/kcc/kcc.go
  pkg/controller/kcc/kcc_test.go
  pkg/controller/kcc/kcct.go
  pkg/controller/kcc/kcct_test.go
  pkg/controller/kcc/util/kcct.go
  pkg/util/kcct.go
Labels: enhancement, workflow/need-review

#123 Network bandwidth allocation
  cmd/katalyst-agent/app/options/qrm/network_plugin.go
  pkg/agent/qrm-plugins/network/state/checkpoint.go
  pkg/agent/qrm-plugins/network/state/state.go
  pkg/agent/qrm-plugins/network/state/state_checkpoint.go
  pkg/agent/qrm-plugins/network/state/state_net.go
  pkg/agent/qrm-plugins/network/state/util.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go
  pkg/agent/qrm-plugins/network/staticpolicy/util.go
  pkg/agent/qrm-plugins/util/util.go
  pkg/config/agent/qrm/network_plugin.go
  pkg/util/general/common.go
Labels: workflow/merge-ready

#190 fix(qrm): fix network plugin possible memory leak
  pkg/agent/qrm-plugins/network/staticpolicy/policy.go
Labels: workflow/need-review

#192 feat(sysadvisor): add more advisor metrics
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
Labels: workflow/merge-ready

#194 feat(sysadvisor): add metrics for memory advisor
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
Labels: enhancement, workflow/merge-ready

#193 fix(qrm): add rm/add container with advisor for memory plugin
  pkg/agent/qrm-plugins/advisorsvc/advisor_svc_stub.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
Labels: workflow/merge-ready

#198 add memory usage metric
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#197 feat(qrm): add advisor metrics for memory plugin
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/util/consts.go
Labels: workflow/need-review

#196 fix kcc and target resource modify no trigger others update
  pkg/controller/kcc/cnc_test.go
  pkg/controller/kcc/kcc_test.go
  pkg/controller/kcc/kcct.go
  pkg/controller/kcc/kcct_test.go
  pkg/controller/kcc/util/kcct.go
  pkg/controller/spd/spd_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#199 feat(qrm): modify memory control knob handler signature to add more utils convenient for handlers registered out of policy itself
  pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/policy_control_knob_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
Labels: workflow/merge-ready

#195 fix(qrm): return an error if no available nics on a node
  pkg/agent/qrm-plugins/network/state/util.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go
  pkg/agent/qrm-plugins/network/staticpolicy/util.go
Labels: workflow/merge-ready

#200 feat(sysadvisor): add indicator cpu usage ratio in rama policy for share region
  go.mod
  go.sum
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go
  pkg/agent/sysadvisor/types/types.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_base.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
Labels: workflow/merge-ready

#203 adding support to periodicalhandler manager in memory plugin
  cmd/katalyst-agent/app/agent/qrm/memory_plugin.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
Labels: enhancement, workflow/need-review

#201 fix(sysadvisor): wait for metrics fetcher synced once when starting up
  pkg/agent/sysadvisor/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/qosaware/qos_aware_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/test/sysadvisor_test.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/metaserver/agent/metric/metric.go
  pkg/metaserver/config/manager_test.go
Labels: bug, workflow/need-review

#206 refine malachite metrics to unified units
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
Labels: documentation, workflow/need-review, workflow/merge-ready

#207 chores(eviction): rename metric
  pkg/agent/evictionmanager/eviction_resp_collector.go
  pkg/agent/evictionmanager/manager.go
Labels: bug, workflow/need-review, workflow/merge-ready

#208 fix(sysadvisor): replace memory avaiable metric
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
Labels: bug, workflow/need-review, workflow/merge-ready

#211 refactor(sysadvisor): set min reserved memory limit for reclaim group
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go
Labels: enhancement, workflow/merge-ready

#209 enhance cpu advisor robustness
  pkg/agent/sysadvisor/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/metric-emitter/metric_emitter_test.go
  pkg/agent/sysadvisor/plugin/qosaware/qos_aware_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/server.go
  pkg/agent/sysadvisor/sysadvisor.go
  pkg/agent/sysadvisor/test/metacache_test.go
  pkg/agent/sysadvisor/test/sysadvisor_test.go
  pkg/agent/sysadvisor/types/cpu.go
  pkg/agent/sysadvisor/types/types.go
Labels: workflow/merge-ready

#210 refactor spd fetcher to async get spd from remote
  cmd/katalyst-agent/app/options/global/metaserver.go
  pkg/metaserver/metaserver_test.go
  pkg/metaserver/spd/cache.go
  pkg/metaserver/spd/fetcher.go
  pkg/metaserver/spd/fetcher_test.go
  pkg/metaserver/spd/manager_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#225 feat(qrm): judge shoudSharedCoresRampUp to avoid vibrating in takeover procedure
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#226 fix advisor issues
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
Labels: workflow/need-review

#218 refine kcmas to support multiple host ips
  pkg/custom-metric/collector/prometheus/collector_promethes.go
  pkg/custom-metric/collector/prometheus/collector_test.go
  pkg/custom-metric/collector/prometheus/scrape.go
  pkg/util/native/container.go
  pkg/util/native/pods.go
  pkg/util/native/pods_test.go
  pkg/util/service-discovery/discovery.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#228 fix(qrm): still try to ramp up if specified pool entry doesn't exist
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
Labels: bug, workflow/merge-ready

#231 fix lifecycle agent pod ready check
  pkg/controller/lifecycle/agent-healthz/healthz_controller.go
  pkg/controller/lifecycle/agent-healthz/healthz_controller_test.go
  pkg/controller/lifecycle/cnc_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#230 fix bugs for justifying isolation region names
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#232 fix bugs for isolation ownerpool setting and support multiple containers to share region
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
Labels: bug, workflow/need-review, workflow/merge-ready

#233 some rand functions are deprecated
  cmd/katalyst-agent/main.go
  cmd/katalyst-controller/main.go
  cmd/katalyst-metric/main.go
  cmd/katalyst-scheduler/main.go
  cmd/katalyst-webhook/main.go
  pkg/agent/qrm-plugins/network/staticpolicy/util.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
Labels: Chore, workflow/need-review

#235 fix(qrm): mem plugin pushes containers to mem adviosr at starting
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
Labels: bug, workflow/need-review, workflow/merge-ready

#234 Fix reporter plugin re-register data loss
  pkg/agent/resourcemanager/fetcher/manager.go
  pkg/agent/resourcemanager/fetcher/plugin/endpoint.go
  pkg/agent/resourcemanager/fetcher/plugin/endpoint_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#236 fix invalid network reservation for network plugin
  pkg/agent/qrm-plugins/network/state/util.go
Labels: bug, workflow/need-review, workflow/merge-ready

#238 fallback to canonical when reclaim disabled; add buffer ratio for cpu estimation
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
Labels: workflow/need-review, workflow/merge-ready

#242 chore(doc): update enhanced k8s installation guide
  docs/install-enhanced-k8s.md
Labels: documentation, workflow/need-review, workflow/merge-ready

#244 chore(doc): update enhanced k8s installation guide for head
  docs/install-enhanced-k8s.md
Labels: documentation, workflow/need-review, workflow/merge-ready

#245 fix and complement region tags
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/types/cpu.go
Labels: workflow/merge-ready

#243 refactor(sysadvisor): refine log format
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
Labels: style, workflow/merge-ready

#248 fix kcmas use label selector failed
  pkg/custom-metric/store/local/local_store.go
Labels: bug, workflow/need-review, workflow/merge-ready

#247 fix cnc update
  pkg/controller/kcc/cnc.go
  pkg/controller/kcc/cnc_test.go
  pkg/controller/lifecycle/cnc.go
  pkg/controller/lifecycle/cnc_test.go
  pkg/controller/lifecycle/cnr.go
  pkg/controller/lifecycle/cnr_test.go
Labels: bug, workflow/need-review, workflow/merge-ready
