Repository kubewharf/katalyst-core, pull requests merged in 2023-10, with the labels that each got.

#296 enhancement(eviction): numa pressure support victim minimum usage thr…
  cmd/katalyst-agent/app/options/dynamic/adminqos/eviction/memory_pressure_eviction.go
  go.mod
  go.sum
  pkg/agent/evictionmanager/plugin/memory/numa_pressure.go
  pkg/agent/evictionmanager/plugin/memory/numa_pressure_test.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure_test.go
  pkg/config/agent/dynamic/adminqos/eviction/memory_pressure_eviction.go
  pkg/metaserver/agent/metric/helper/system.go
Labels: enhancement, workflow/need-review

#304 fix: code comment linked address
  cmd/base/healthz.go
Labels: documentation, workflow/merge-ready

#286 Updating cpu_request of containerInfo in periodicWork of MetaCachePlugin
  pkg/agent/sysadvisor/plugin/metacache/metacache.go
  pkg/agent/sysadvisor/types/helper.go
Labels: bug, workflow/merge-ready

#308 chore: ignore test coverage profile files
  .gitignore
Labels: documentation, workflow/merge-ready

#310 move locking file metrics name to const and renaming
  cmd/katalyst-agent/app/agent.go
Labels: chore, workflow/need-review, workflow/merge-ready

#309 fix: character type
  pkg/util/process/http.go
Labels: chore, workflow/merge-ready

#306 Fix calculation of rate metrics
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
Labels: bug, workflow/merge-ready

#313 increase the log level of getting object failed when check internal metric
  pkg/custom-metric/store/local/local_store.go
Labels: chore, workflow/need-review, workflow/merge-ready

#312 refine kcmas and support aggregating logic in local cache
  go.mod
  go.sum
  pkg/custom-metric/provider/provider.go
  pkg/custom-metric/provider/util.go
  pkg/custom-metric/store/data/aggregator.go
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/cache_test.go
  pkg/custom-metric/store/data/internal.go
  pkg/custom-metric/store/data/types/aggragated.go
  pkg/custom-metric/store/data/types/metric.go
  pkg/custom-metric/store/data/types/series.go
  pkg/custom-metric/store/data/types/util.go
  pkg/custom-metric/store/local/local_store.go
  pkg/custom-metric/store/local/server.go
  pkg/custom-metric/store/remote/remote_store.go
  pkg/custom-metric/store/store.go
  pkg/util/general/deepcopy.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#315 enhancement(kcmas): emit metric latency
  pkg/custom-metric/provider/provider.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#297 enhancement(sysadvisor): skip the containers if cache usage less then…
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/memory_advisor.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/plugins/cache_reaper.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/plugins/common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/cache_reaper.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/memory_advisor.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/plugins/cache_reaper.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/plugins/common.go
Labels: enhancement, workflow/merge-ready

#316 fix(eviction): parse container id when stop container
  pkg/agent/evictionmanager/podkiller/killer.go
  pkg/agent/evictionmanager/podkiller/killer_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#317 decode metric list according to metric name whether is aggregator metric
  pkg/controller/lifecycle/cnr_test.go
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/cache_test.go
  pkg/custom-metric/store/data/internal.go
  pkg/custom-metric/store/data/types/aggragated.go
  pkg/custom-metric/store/data/types/util.go
  pkg/custom-metric/store/local/local_store.go
  pkg/custom-metric/store/remote/remote_store.go
Labels: bug, workflow/need-review, workflow/merge-ready

#319 fix window seconds
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/types/aggragated.go
Labels: bug, workflow/need-review, workflow/merge-ready

#318 feature(kcmas): scrape with basic auth
  cmd/base/context.go
  cmd/katalyst-metric/app/options/collector.go
  pkg/config/metric/collector.go
  pkg/custom-metric/collector/prometheus/collector_promethes.go
  pkg/custom-metric/collector/prometheus/collector_test.go
  pkg/custom-metric/collector/prometheus/scrape.go
  pkg/custom-metric/collector/prometheus/scrape_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#320 check coreCount within AggregateCoreMetric
  pkg/util/metric/store_util.go
Labels: bug, workflow/merge-ready

#321 feat(advisor): support disable registered model result fetcher
  pkg/agent/sysadvisor/plugin/inference/inference.go
  pkg/agent/sysadvisor/plugin/inference/inference_test.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#322 Fix problem of divided by 0 in memory bandwidth calculation
  pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
Labels: bug, workflow/merge-ready

#323 feat(http): non-strict authentication
  cmd/base/context.go
  cmd/base/options/auth.go
  cmd/base/options/generic.go
  cmd/katalyst-agent/app/agent.go
  cmd/katalyst-agent/app/agent/eviction.go
  pkg/config/generic/auth.go
  pkg/config/generic/generic_base.go
  pkg/util/process/http.go
  pkg/util/process/http_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#328 kcams add collector scrape out of date metrics
  pkg/custom-metric/collector/prometheus/collector_promethes.go
  pkg/custom-metric/collector/prometheus/scrape.go
Labels: chore, workflow/need-review, workflow/merge-ready

#229 feat(overcommit): add node overcommit webhook
  cmd/katalyst-webhook/app/webhook.go
  cmd/katalyst-webhook/app/webhook/mutating/node.go
  pkg/util/native/resources.go
  pkg/util/native/resources_test.go
  pkg/webhook/mutating/node/allocatable_mutator.go
  pkg/webhook/mutating/node/node.go
  pkg/webhook/mutating/node/node_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#333 fix(eviction): panic when get evict pods
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton.go
Labels: bug, workflow/need-review, workflow/merge-ready

#332 add pod_cpu_cpi in custom metric
  go.mod
  go.sum
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
Labels: workflow/merge-ready

#325 add standard framework for service discovery
  cmd/katalyst-metric/app/options/store.go
  pkg/config/generic/service_discovery.go
  pkg/config/metric/store.go
  pkg/custom-metric/provider/provider_test.go
  pkg/custom-metric/store/remote/remote_store.go
  pkg/custom-metric/store/remote/sharding.go
  pkg/util/service-discovery/dummy_sd.go
  pkg/util/service-discovery/interface.go
  pkg/util/service-discovery/pod_single_port_sd.go
  pkg/util/service-discovery/service_single_port_sd.go
  pkg/util/service-discovery/service_single_port_sd_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#327 feat(eviction): system free memory threshold minimum
  cmd/katalyst-agent/app/options/dynamic/adminqos/eviction/memory_pressure_eviction.go
  go.mod
  go.sum
  pkg/agent/evictionmanager/plugin/memory/numa_pressure_test.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure_test.go
  pkg/config/agent/dynamic/adminqos/eviction/memory_pressure_eviction.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#329 perf(kcmas): performance optimization
  pkg/custom-metric/provider/provider.go
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/cache_test.go
  pkg/custom-metric/store/data/internal.go
  pkg/custom-metric/store/data/types/aggragated.go
  pkg/custom-metric/store/data/types/series.go
  pkg/metrics/tag_wrapper_metrics.go
  pkg/util/general/deepcopy.go
Labels: enhancement, workflow/need-review, workflow/merge-ready
