Repository kubewharf/katalyst-core, pull requests merged in 2023-06, with the labels that each got.

#87 feat(eviction): rss overuse eviction base on request
  pkg/agent/evictionmanager/plugin/memory/rss_overuse.go
  pkg/agent/evictionmanager/plugin/memory/rss_overuse_test.go
  pkg/config/agent/eviction/memory_pressure_eviction_plugin.go
  pkg/util/qos/mem_enhancement.go
Labels: enhancement, workflow/merge-ready

#83 fix(sysadvisor): return notFound error when spd name not found
  pkg/metaserver/spd/fetcher.go
Labels: bug, workflow/merge-ready

#91 fix(sysadvisor): create new checkpoint if fetching it failed
  pkg/agent/sysadvisor/metacache/metacache.go
Labels: bug, workflow/need-review

#90 fix(external_mgr): fix adding cgroup id log format typo
  pkg/metaserver/external/cgroupid/manager_linux.go
Labels: workflow/need-review

#93 add GetContainerID and GetContainerEnvs to pod util
  pkg/metaserver/agent/pod/pod.go
  pkg/metaserver/agent/pod/pod_stub.go
  pkg/util/native/pods.go
  pkg/util/native/pods_test.go
Labels: Chore, workflow/merge-ready

#88 feat(qrm): qrm cpu/mem plugins support identifying debug pod
  cmd/katalyst-agent/app/options/qrm/qrm_base.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/util/util.go
  pkg/config/agent/qrm/qrm_base.go
Labels: workflow/need-review

#74 fix(sysadvisor): set estimated resource as pod request when ramping up
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
Labels: bug, workflow/merge-ready

#95 change log format to export the entire pkg name
  pkg/util/general/log.go
  pkg/util/general/log_test.go
Labels: workflow/need-review, workflow/merge-ready

#97 support to use logger with pre-defined prefix
  pkg/agent/sysadvisor/test/metacache_test.go
  pkg/util/general/log.go
  pkg/util/general/log_test.go
Labels: workflow/need-review, workflow/merge-ready

#98 fix: avoid fetching empty metrics
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
Labels: bug, workflow/merge-ready

#99 exchange round and slowdown in cpu regulator
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go
Labels: workflow/merge-ready

#100 chore(eviction): dry-run metric add pod name tag
  pkg/agent/evictionmanager/eviction_resp_collector.go
Labels: enhancement, workflow/merge-ready

#89 Support isolation pools
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
  pkg/agent/sysadvisor/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_load.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/helper.go
  pkg/agent/sysadvisor/types/helper.go
  pkg/agent/sysadvisor/types/types.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/metric.go
  pkg/util/general/common.go
Labels: workflow/need-review, workflow/merge-ready

#104 fix(eviciton): apply eviction configuration
  cmd/katalyst-agent/app/options/dynamic/dynamic_base.go
Labels: bug, workflow/merge-ready

#106 feat(advisor_proto): design a general api between qrm plugins and advisors
  Makefile
  pkg/agent/qrm-plugins/advisorsvc/advisor_svc.pb.go
  pkg/agent/qrm-plugins/advisorsvc/advisor_svc.proto
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpuadvisor/cpu.pb.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpuadvisor/cpu.pb_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpuadvisor/cpu.proto
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpuadvisor/qos_aware_client_stub.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpuadvisor/qos_aware_client_stub_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server_test.go
Labels: workflow/merge-ready

#108 feat(eviciton): rss overuse eviction support pod filter
  cmd/katalyst-agent/app/options/eviction/memory_pressure_eviction_plugin.go
  cmd/katalyst-agent/app/options/eviction/memory_pressure_eviction_plugin_test.go
  pkg/agent/evictionmanager/plugin/memory/rss_overuse.go
  pkg/agent/evictionmanager/plugin/memory/rss_overuse_test.go
  pkg/config/agent/eviction/memory_pressure_eviction_plugin.go
Labels: enhancement, workflow/need-review

#110 refine(qrm): network plugin refers api resource declaration
  go.mod
  go.sum
  pkg/agent/qrm-plugins/network/staticpolicy/policy.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go
  pkg/agent/qrm-plugins/network/staticpolicy/util.go
Labels: style, workflow/merge-ready

#105 implement rama policy framework with pid controller
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go
  pkg/agent/sysadvisor/types/types.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_base.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/metric.go
  pkg/util/general/common.go
Labels: enhancement, workflow/merge-ready

#111 deprecate region headroom policies
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_utlilization.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_utlilization_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/types/types.go
Labels: Chore, workflow/need-review

#112 calculate container cpi by cycles and instructions
  pkg/metaserver/agent/metric/malachite/cgroup/types.go
  pkg/metaserver/agent/metric/metric.go
Labels: bug, workflow/need-review

#113 add deadband for pid controller to avoid hunting
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go
  pkg/agent/sysadvisor/types/types.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
Labels: enhancement, workflow/need-review

#116 fix(sysadvisor): fix sequential bugs in pid controller
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
Labels: bug, workflow/need-review

#114 feat(qrm): network plugin deal with sidecars
  pkg/agent/qrm-plugins/network/staticpolicy/policy.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go
  pkg/agent/qrm-plugins/network/staticpolicy/util.go
Labels: workflow/merge-ready

#115 fix(qrm): fix numa_binding hint calculation
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go
  pkg/agent/qrm-plugins/util/util.go
Labels: workflow/merge-ready

#118 refactor(util): refine some function related to memory enhancement
  pkg/util/eviction/eviction.go
  pkg/util/qos/mem_enhancement.go
Labels: workflow/merge-ready

#117 increase rama policy robustness
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/pid.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
  pkg/agent/sysadvisor/types/consts.go
  pkg/agent/sysadvisor/types/types.go
Labels: enhancement, workflow/merge-ready

#122 refine metric interface to store timestamp
  pkg/agent/evictionmanager/plugin/memory/helper.go
  pkg/agent/evictionmanager/plugin/memory/helper_test.go
  pkg/agent/evictionmanager/plugin/memory/numa_pressure_test.go
  pkg/agent/evictionmanager/plugin/memory/rss_overuse_test.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go
  pkg/agent/sysadvisor/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/metric-emitter/metric_emitter.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/external/external.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/metric_emitter_plugin.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_load.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_util.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/agent/metric/malachite/cgroup/types.go
  pkg/metaserver/agent/metric/metric.go
  pkg/metaserver/agent/metric/metric_calculation.go
  pkg/metaserver/agent/metric/metric_test.go
  pkg/util/general/common.go
  pkg/util/metric/store.go
  pkg/util/metric/store_test.go
  pkg/util/metric/store_util.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#121 cpu advisor support get pod indicator target from spd
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/types/types.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_base.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
  pkg/metaserver/metaserver.go
  pkg/metaserver/spd/manager.go
  pkg/metaserver/spd/manager_test.go
  pkg/util/spd_indicator.go
Labels: enhancement, workflow/merge-ready

#125 enhancement(eviction): avoid misjudgment by checking metric timestamp
  pkg/agent/evictionmanager/plugin/memory/helper.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure_test.go
Labels: enhancement, workflow/merge-ready
