Repository kubewharf/katalyst-core, pull requests merged in 2023-09, with the labels that each got.

#249 fix(util): return nil when samples pool is not filled
  pkg/util/general/window.go
  pkg/util/general/window_test.go
Labels: bug, workflow/merge-ready

#251 fix memory leak by close all response body
  pkg/custom-metric/store/remote/remote_store.go
  pkg/custom-metric/store/remote/sharding.go
Labels: bug, workflow/need-review, workflow/merge-ready

#254 getZoneAllocations filter out failed and succeeded pod
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go
Labels: bug, workflow/need-review

#257 feat(eviction): support container killer
  cmd/katalyst-agent/app/agent/eviction.go
  cmd/katalyst-agent/app/options/eviction/eviction_base.go
  pkg/agent/evictionmanager/const.go
  pkg/agent/evictionmanager/manager.go
  pkg/agent/evictionmanager/manager_test.go
  pkg/agent/evictionmanager/podkiller/killer.go
  pkg/agent/evictionmanager/podkiller/killer_test.go
  pkg/config/agent/eviction/eviciton_base.go
  pkg/consts/common.go
  pkg/consts/evictionmanager.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#259 fix(sysadvisor): assemble duplicate block
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
Labels: bug, workflow/merge-ready

#262 fix(sysadvisor): fix invalid cpulimit
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
Labels: bug, workflow/need-review, workflow/merge-ready

#261 GetTopologyZones return error if list pod resources empty
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#264 resource eviction ThresholdGetter support threshold not set
  pkg/agent/evictionmanager/plugin/reclaimed_resources.go
  pkg/agent/evictionmanager/plugin/resources.go
Labels: chore, workflow/merge-ready

#263 fix owner pool name for isolated container
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#250 fix(controller): fix cnr residue when node deletion
  cmd/katalyst-agent/app/options/reporter/reporter_base.go
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
  pkg/config/agent/reporter/reporter_base.go
  pkg/controller/lifecycle/cnr.go
Labels: bug, workflow/need-review, workflow/merge-ready

#266 fix(agent): fix cnr residue when node deletion
  cmd/katalyst-agent/app/options/reporter/reporter_base.go
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
  pkg/config/agent/reporter/reporter_base.go
  pkg/controller/lifecycle/cnr.go
Labels: bug, workflow/need-review, workflow/merge-ready

#267 fix set-pool-regions in sysadvisor: always use origin owner pool name
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
Labels: bug, workflow/need-review, workflow/merge-ready

#265 fix KatalystCustomConfigTargetHandler to avoid cnc being cleared when cache no synced in restart
  pkg/controller/kcc/cnc.go
  pkg/controller/kcc/kcc.go
  pkg/controller/kcc/kcct.go
  pkg/controller/kcc/target/target_handler.go
Labels: bug, workflow/need-review, workflow/merge-ready

#269 fix(sysadvisor): set share region owner pool as container origin owne…
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
Labels: bug, workflow/merge-ready

#272 fix(sysadvisor): avoid gc living containers' original owner pools
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
Labels: workflow/need-review, workflow/merge-ready

#274 fix(qrm): clean pool concerning owner pool name instead of specified pool
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
Labels: workflow/merge-ready

#273 refactor: refine memory log format
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
Labels: enhancement, workflow/merge-ready

#276 hint got from extra state file must be subset of available NUMAs
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go
  pkg/agent/qrm-plugins/util/util.go
Labels: bug, workflow/need-review

#275 refactor(sysadvisor): bind reclaim_cores contianers to non-exclusive …
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memset_binder.go
Labels: enhancement, workflow/need-review

#277 always set the min-value for isolation bound as 1 core
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
Labels: bug, workflow/need-review, workflow/merge-ready

#278 feat(sysadvisor): support numa aware memory headroom policy
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware_test.go
  pkg/agent/sysadvisor/types/memory.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
Labels: enhancement, workflow/merge-ready

#280 PluginRegistrationWrapper inherit GenericPlugin directly
  go.mod
  go.sum
Labels: chore, workflow/need-review, workflow/merge-ready

#282 fix(sysadvisor): consider pod reclaim disabled
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/types/helper.go
Labels: bug, workflow/merge-ready

#281 add metrics for failed events
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
Labels: enhancement, workflow/merge-ready

#283 Add device io stat metrics
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/util/metric/store.go
Labels: enhancement, workflow/merge-ready

#288 fix(sysadvisor): check pod number for dedicated region
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/types/helper.go
Labels: bug, workflow/merge-ready

#289 fix region info clone no clone region status
  pkg/agent/sysadvisor/types/helper.go
Labels: bug, workflow/need-review, workflow/merge-ready

#290 fix node_advisor_knob_status tag
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/advisor.go
  pkg/agent/sysadvisor/types/helper.go
Labels: bug, workflow/need-review, workflow/merge-ready

#291 feat(sysadvisor): set a relatively large threshold for early cache re…
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/memory_advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/memory_advisor.go
Labels: enhancement, workflow/merge-ready

#279 feat(auth): auth framework
  cmd/base/context.go
  cmd/base/context_fake.go
  cmd/base/options/auth.go
  cmd/base/options/generic.go
  cmd/katalyst-agent/app/options/eviction/eviction_base.go
  go.mod
  go.sum
  pkg/agent/evictionmanager/endpoint/endpoint.go
  pkg/agent/evictionmanager/manager.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton.go
  pkg/config/agent/eviction/eviciton_base.go
  pkg/config/generic/auth.go
  pkg/config/generic/generic_base.go
  pkg/util/credential/authorization/authorizations.go
  pkg/util/credential/authorization/insecure.go
  pkg/util/credential/authorization/insecure_test.go
  pkg/util/credential/authorization/secret.go
  pkg/util/credential/authorization/secret_test.go
  pkg/util/credential/authorization/static.go
  pkg/util/credential/authorization/static_test.go
  pkg/util/credential/basic.go
  pkg/util/credential/basic_test.go
  pkg/util/credential/credentials.go
  pkg/util/credential/insecure.go
  pkg/util/credential/insecure_test.go
  pkg/util/process/http.go
  pkg/util/process/http_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#292 fix kcmas precise when some metric with small value
  pkg/custom-metric/collector/prometheus/scrape.go
  pkg/custom-metric/provider/provider_test.go
  pkg/custom-metric/provider/util.go
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/const.go
Labels: bug, workflow/need-review, workflow/merge-ready

#293 feat(sysadvisor): bind memset to no pressure NUMAs
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memset_binder.go
Labels: enhancement, workflow/merge-ready

#294 feat(sysadvisor): add metrics for headroom
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
Labels: enhancement, workflow/need-review
