Repository kubewharf/katalyst-core, pull requests merged in 2023-07, with the labels that each got.

#130 switch to full path of general logging
  pkg/util/general/log.go
  pkg/util/general/log_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#132 refactor adminqos definition list member remove omitempty json flag
  go.mod
  go.sum
  pkg/config/agent/dynamic/adminqos/eviction/eviction_base.go
  pkg/metaserver/config/checkpoint_test.go
  pkg/util/kcct_test.go
Labels: Chore, workflow/merge-ready

#126 refine qosaware resource server and introduce memory advisor framework
  cmd/katalyst-agent/app/options/global/qrmadvisor.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/memory_advisor.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/server/qrm_server.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/plugin.go
  pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/helper.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/server.go
  pkg/agent/sysadvisor/test/sysadvisor_test.go
  pkg/agent/sysadvisor/types/cpu.go
  pkg/agent/sysadvisor/types/helper.go
  pkg/agent/sysadvisor/types/memory.go
  pkg/agent/sysadvisor/types/types.go
  pkg/config/agent/global/qrmadvisor.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/memory_advisor.go
Labels: enhancement, workflow/merge-ready

#131 supplement metric and expand the ability to add external metric
  pkg/consts/common.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/agent/metric/malachite/cgroup/types.go
  pkg/metaserver/agent/metric/malachite/system/types.go
  pkg/metaserver/agent/metric/metric.go
  pkg/metaserver/agent/metric/metric_calculation.go
Labels: workflow/need-review, workflow/merge-ready

#133 enhancement(eviction): use duration as threshold instead of times
  cmd/katalyst-agent/app/options/dynamic/adminqos/eviction/memory_pressure_eviction.go
  go.mod
  go.sum
  pkg/agent/evictionmanager/plugin/memory/helper.go
  pkg/agent/evictionmanager/plugin/memory/numa_pressure_test.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure_test.go
  pkg/config/agent/dynamic/adminqos/eviction/memory_pressure_eviction.go
  pkg/metaserver/config/manager_test.go
  pkg/util/kcct_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#134 fix(sysadvisor): make resource updating not blocked by resource server
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/memory_advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go
  pkg/agent/sysadvisor/types/cpu.go
  pkg/agent/sysadvisor/types/memory.go
Labels: bug, workflow/merge-ready

#135 feat(metaserver): support collecting metrics for qos level
  pkg/consts/metric.go
  pkg/metaserver/agent/agent.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/agent/metric/metric.go
  pkg/metaserver/agent/metric/metric_test.go
  pkg/metaserver/metaserver_test.go
  pkg/util/metric/store.go
Labels: enhancement, workflow/merge-ready

#139 fix(sysadvisor): set a buffer for the channel
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
Labels: bug, workflow/need-review

#140 feat(qrm): define memory advisor control knob constants
  pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/const.go
Labels: workflow/merge-ready

#120 feat(qrm): use asynchronous workers to drop cache and migrate pages
  cmd/katalyst-agent/app/options/qrm/memory_plugin.go
  go.mod
  go.sum
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/util_unsupported.go
  pkg/agent/qrm-plugins/util/util.go
  pkg/config/agent/qrm/memory_plugin.go
  pkg/util/asyncworker/async_workers.go
  pkg/util/asyncworker/async_workers_test.go
  pkg/util/asyncworker/helpers.go
  pkg/util/asyncworker/types.go
  pkg/util/cgroup/manager/cgroup.go
  pkg/util/cgroup/manager/cgroup_test.go
Labels: enhancement, workflow/merge-ready

#145 chore(ci): always upload coverage file
  .github/workflows/ci.yml
  codecov.yml
Labels: Chore, workflow/need-review, workflow/merge-ready

#147 chore(ci): ignore codecov check if the number of changed lines is smaller than 10
  .github/workflows/ci.yml
  codecov.yml
Labels: Chore, workflow/need-review, workflow/merge-ready

#146 filter out none-matched namespance in kcmas
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/cache_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#152 move malachite client from global varibales to malachite fetcher
  pkg/controller/lifecycle/cnr_test.go
  pkg/metaserver/agent/metric/malachite/cgroup/cgroup.go
  pkg/metaserver/agent/metric/malachite/cgroup/cgroup_test.go
  pkg/metaserver/agent/metric/malachite/client/client.go
  pkg/metaserver/agent/metric/malachite/system/system.go
  pkg/metaserver/agent/metric/malachite/system/system_test.go
  pkg/metaserver/agent/metric/metric.go
  pkg/metaserver/external/cgroupid/manager_linux_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#149 chore(doc): fix link in installation guide
  docs/install-enhanced-k8s.md
Labels: documentation, workflow/merge-ready

#143 memory advisor plugins
  pkg/agent/evictionmanager/plugin/memory/helper.go
  pkg/agent/evictionmanager/plugin/memory/helper_test.go
  pkg/agent/evictionmanager/plugin/memory/numa_pressure.go
  pkg/agent/evictionmanager/plugin/memory/numa_pressure_test.go
  pkg/agent/evictionmanager/plugin/memory/rss_overuse.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/cache_reaper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memset_binder.go
  pkg/agent/sysadvisor/types/helper.go
  pkg/metaserver/agent/metric/helper/consts.go
  pkg/metaserver/agent/metric/helper/container.go
  pkg/metaserver/agent/metric/helper/pod.go
  pkg/metaserver/agent/metric/helper/system.go
  pkg/util/machine/util.go
Labels: enhancement, workflow/merge-ready

#155 add support to define kcmas metric dynamically
  cmd/katalyst-agent/app/options/sysadvisor/metric-emitter/metric_emitter_plugin.go
  go.mod
  go.sum
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
  pkg/config/agent/sysadvisor/metric-emitter/metric_emitter_plugin.go
  pkg/controller/spd/spd_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#153 feat(util): add periodical handlers util
  cmd/katalyst-agent/app/agent/qrm/cpu_plugin.go
  cmd/katalyst-agent/app/enableagents.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/utilcomponent/periodicalhandler/consts/consts.go
  pkg/agent/utilcomponent/periodicalhandler/periodical_handler.go
  pkg/agent/utilcomponent/periodicalhandler/periodical_handler_test.go
  pkg/controller/spd/spd_test.go
  pkg/util/process/http_test.go
Labels: workflow/need-review, workflow/merge-ready

#156 fix(sysadvisor): Pod CPU request should only be used as estimated val…
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
Labels: bug, workflow/merge-ready

#154 refine the implementation for malachite and machine info
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/const.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/policy_control_knob_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/cache_reaper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memset_binder.go
  pkg/metaserver/agent/agent.go
  pkg/metaserver/agent/cnc/cnc.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
  pkg/metaserver/agent/metric/malachite/fetcher_test.go
  pkg/metaserver/agent/metric/metric.go
  pkg/metaserver/config/checkpoint.go
  pkg/metaserver/config/manager_test.go
  pkg/metaserver/metaserver_test.go
  pkg/util/machine/util.go
Labels: style, workflow/need-review, workflow/merge-ready

#151 feat(*): add switches to enable only components required for topology-aware scheduling
  cmd/katalyst-agent/app/options/global/metaserver.go
  cmd/katalyst-controller/app/controller/lifecycle.go
  cmd/katalyst-controller/app/options/lifecycle.go
  pkg/config/agent/global/metaserver.go
  pkg/config/controller/lifecycle.go
  pkg/metaserver/agent/agent.go
  pkg/metaserver/agent/cnc/fake_cnc.go
  pkg/metaserver/metaserver_test.go
Labels: enhancement, workflow/need-review

#163 support to register external object fecthers in metaserver
  pkg/metaserver/agent/agent.go
  pkg/metaserver/agent/agent_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#165 refactor sysadvisor cpu headroom assembler by abstract the logic of util-based capacity estimation
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_util.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
Labels: Chore, workflow/need-review

#162 refactor(agent): change entrance function signature
  cmd/katalyst-agent/app/agent.go
  cmd/katalyst-agent/main.go
Labels: workflow/merge-ready

#166 remove unused sliding window in GenericHeadroomManager
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic.go
Labels: bug, workflow/need-review, workflow/merge-ready

#167 add flags to enable alert logging level
  cmd/base/options/generic.go
  cmd/base/options/log.go
  pkg/metrics/metrics-pool/otel_prom_metrics_mux.go
  pkg/util/general/log.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#164 feat: introduce percentile aggregator for window sliding
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/reporter/headroom_reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/cpu.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/memory.go
  pkg/config/agent/sysadvisor/qosaware/reporter/headroom_reporter.go
  pkg/util/general/window.go
  pkg/util/general/window_test.go
Labels: enhancement, workflow/merge-ready

#158 fix(sysadvisor): set numa capicity as requirement of numabinding pods when reclaimed disabled
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go
  pkg/metaserver/spd/manager.go
  pkg/util/machine/machine.go
  pkg/util/machine/machine_linux.go
  pkg/util/machine/topology.go
Labels: bug, workflow/merge-ready

#168 fix(controller): fix bug if cnr or cnc is not found in lister
  pkg/controller/lifecycle/cnr.go
Labels: bug, workflow/need-review, workflow/merge-ready

#150 feat(reporter): report topology policy to kcnr
  cmd/katalyst-agent/app/options/global/base.go
  cmd/katalyst-agent/app/options/global/metaserver.go
  cmd/katalyst-agent/app/options/reporter/kubelet_plugin.go
  pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go
  pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin_test.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/interface.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topologyAdapter.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topologyAdapter_test.go
  pkg/config/agent/global/base.go
  pkg/config/agent/global/metaserver.go
  pkg/config/agent/reporter/kubelet_plugin.go
  pkg/metaserver/agent/agent.go
  pkg/metaserver/agent/agent_test.go
  pkg/metaserver/agent/kubeletconfig/fake_kubeletconfig.go
  pkg/metaserver/agent/kubeletconfig/kubeletconfig.go
  pkg/util/cnr.go
  pkg/util/native/kubelet.go
  pkg/util/native/kubelet_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#159 feat(metaserver): support getting pods from kubelet secure port
  cmd/katalyst-agent/app/options/global/metaserver.go
  pkg/config/agent/global/metaserver.go
  pkg/metaserver/agent/pod/kubelet.go
  pkg/metaserver/agent/pod/pod.go
Labels: enhancement, workflow/draft, workflow/merge-ready

#170 fix(assemble): fix using fake NUMA ID to find non binding numas
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_dedicated.go
  pkg/agent/sysadvisor/types/helper.go
Labels: bug, workflow/merge-ready

#172 feat: headroom policy for dedicated numa
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go
  pkg/agent/sysadvisor/types/cpu.go
  pkg/agent/sysadvisor/types/helper.go
  pkg/metaserver/spd/manager.go
  pkg/util/general/common.go
  pkg/util/general/common_test.go
Labels: enhancement, workflow/merge-ready

#169 add more metrics in kcmas
  go.mod
  go.sum
  pkg/agent/sysadvisor/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/advisor.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
  pkg/agent/sysadvisor/types/cpu.go
  pkg/metaserver/agent/agent.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/agent/metric/malachite/cgroup/cgroup_test.go
  pkg/metaserver/agent/metric/malachite/cgroup/cri.go
  pkg/metaserver/agent/metric/malachite/client/client.go
  pkg/metaserver/agent/metric/malachite/client/client_cgroup.go
  pkg/metaserver/agent/metric/malachite/client/client_cgroup_test.go
  pkg/metaserver/agent/metric/malachite/client/client_pod.go
  pkg/metaserver/agent/metric/malachite/client/client_pod_test.go
  pkg/metaserver/agent/metric/malachite/client/client_system.go
  pkg/metaserver/agent/metric/malachite/client/client_system_test.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
  pkg/metaserver/agent/metric/malachite/fetcher_test.go
  pkg/metaserver/agent/metric/malachite/types/cgroup.go
  pkg/metaserver/agent/metric/malachite/types/system.go
  pkg/metaserver/metaserver_test.go
  pkg/util/cgroup/common/path.go
Labels: enhancement, workflow/need-review, workflow/merge-ready
