Repository kubewharf/katalyst-core, pull requests merged in 2023-05, with the labels that each got.

#49 emit metrics for pod killing and add tags for victims
  pkg/agent/evictionmanager/manager.go
  pkg/agent/evictionmanager/podkiller/killer.go
  pkg/agent/evictionmanager/podkiller/killer_test.go
  pkg/agent/sysadvisor/plugin/metric-emitter/metric_emitter.go
Labels: workflow/need-review, workflow/merge-ready

#51 fix vpa condition RecommendationApplied
  pkg/controller/vpa/util/api.go
  pkg/controller/vpa/vpa_status.go
  pkg/controller/vpa/vparec.go
  pkg/controller/vpa/vparec_test.go
  pkg/util/vpa.go
Labels: bug, workflow/need-review

#53 refine coding styles for network plugin
  cmd/katalyst-agent/main.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/network/dynamicpolicy/policy.go
  pkg/util/cgroup/common/cgroup_linux.go
  pkg/util/cgroup/common/path.go
  pkg/util/cgroup/common/path_test.go
  pkg/util/cgroup/manager/manager.go
  pkg/util/general/common.go
  pkg/util/general/log.go
  pkg/util/general/log_test.go
  pkg/util/machine/topology.go
  pkg/util/machine/util.go
  pkg/util/machine/util_test.go
Labels: style, workflow/need-review, workflow/merge-ready

#56 fix(qrm): pass ramp up infomation to sys advisor
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
Labels: workflow/need-review

#55 chore(*): add license header check to ci pipeline and fix some related issues
  .github/workflows/ci.yml
  .licenseignore
  Makefile
  ci.yml
  cmd/katalyst-agent/app/agent/qrm/network_plugin.go
  cmd/katalyst-agent/app/options/eviction/cpu_pressure_eviction_plugin.go
  cmd/katalyst-agent/app/options/eviction/memory_pressure_eviction_plugin.go
  cmd/katalyst-agent/app/options/qrm/network_plugin.go
  cmd/katalyst-scheduler/app/server.go
  hack/add-license.sh
  pkg/agent/evictionmanager/plugin/memory_pressure.go
  pkg/agent/evictionmanager/plugin/memory_pressure_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/cpu_eviciton_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_test.go
  pkg/agent/qrm-plugins/network/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/network/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/network/network.go
  pkg/agent/resourcemanager/fetcher/system/systemplugin_test.go
  pkg/agent/sysadvisor/test/metacache_test.go
  pkg/agent/sysadvisor/test/sysadvisor_test.go
  pkg/config/agent/eviction/cpu_pressure_eviction_plugin.go
  pkg/config/agent/eviction/memory_pressure_eviction_plugin.go
  pkg/config/agent/qrm/network_plugin.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/config/config.go
  pkg/metaserver/external/cgroupid/manager.go
  pkg/metaserver/external/cgroupid/manager_linux.go
  pkg/metaserver/external/cgroupid/manager_linux_test.go
  pkg/metaserver/external/cgroupid/manager_unsupported.go
  pkg/metaserver/external/manager.go
  pkg/metaserver/external/manager_linux.go
  pkg/metaserver/external/manager_linux_test.go
  pkg/metaserver/external/manager_unsupported.go
  pkg/util/external/network/manager.go
  pkg/util/external/network/manager_linux.go
  pkg/util/external/network/manager_linux_test.go
  pkg/util/external/network/manager_unsupported.go
  pkg/util/external/rdt/manager.go
  pkg/util/external/rdt/manager_linux.go
  pkg/util/external/rdt/manager_linux_test.go
  pkg/util/external/rdt/manager_unsupported.go
  pkg/util/general/endian.go
  pkg/util/general/sorter.go
  pkg/util/native/pod_sorter.go
  pkg/util/native/pods_test.go
  pkg/util/qos/net_enhancement.go
  pkg/util/qos/net_enhancement_test.go
Labels: Chore, workflow/merge-ready

#58 fix ut failed on macOS
  pkg/util/cgroup/common/cgroup_unsupported.go
Labels: bug, workflow/merge-ready

#47 feat(sysadvisor): support multi share regions
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
  pkg/agent/sysadvisor/types/consts.go
  pkg/util/general/common.go
Labels: enhancement, workflow/need-review

#45 feat(resource) refine resource manager to support newly cnr definition to report enhanced topology information
  Makefile
  go.mod
  go.sum
  pkg/agent/evictionmanager/plugin/reclaimed_resources.go
  pkg/agent/evictionmanager/plugin/reclaimed_resources_test.go
  pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/interface.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/podresourcesserver.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/podresourcesserver_test.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/util.go
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter_test.go
  pkg/agent/resourcemanager/reporter/converter.go
  pkg/agent/resourcemanager/reporter/manager.go
  pkg/agent/resourcemanager/reporter/manager_test.go
  pkg/agent/resourcemanager/reporter/reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/reporter.go
  pkg/client/control/cnr.go
  pkg/custom-metric/collector/prometheus/scrape_test.go
  pkg/scheduler/cache/nodeinfo.go
  pkg/scheduler/eventhandlers/cache_test.go
  pkg/scheduler/plugins/qosawarenoderesources/fit_test.go
  pkg/util/cnr.go
  pkg/util/cnr_test.go
  pkg/util/cnr_topology.go
  pkg/util/general/error.go
  pkg/util/native/resources.go
  pkg/util/syntax/reflect.go
Labels: enhancement, workflow/need-review

#62 fix(sysadvisor): clean up the contianers not existed in checkpoint
  pkg/agent/sysadvisor/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
  pkg/agent/sysadvisor/test/metacache_test.go
  pkg/agent/sysadvisor/types/helper_test.go
Labels: bug, workflow/merge-ready

#59 support utilization based canonical cpu headroom policy
  cmd/katalyst-agent/app/enableagents.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/headroom/policy_base.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/headroom/policy_utilization.go
  pkg/agent/sysadvisor/plugin/plugin.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_utlilization.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_utlilization_test.go
  pkg/agent/sysadvisor/sysadvisor.go
  pkg/agent/sysadvisor/types/types.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/headroom/policy_base.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/headroom/policy_utilization.go
  pkg/metaserver/agent/cnr/cnr_stub.go
  pkg/util/general/log.go
  pkg/util/general/log_test.go
  pkg/util/metric/store_util.go
Labels: enhancement, workflow/merge-ready

#65 support to mark unhealthy for acquiring file locks
  cmd/katalyst-agent/app/agent.go
  cmd/katalyst-agent/app/options/global/base.go
  pkg/config/agent/global/base.go
  pkg/util/general/file.go
  pkg/util/general/file_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#64 feat(sysadvisor): support persist regionEntries
  pkg/agent/sysadvisor/metacache/checkpoint.go
  pkg/agent/sysadvisor/metacache/checkpoint_test.go
  pkg/agent/sysadvisor/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/types/types.go
Labels: enhancement, workflow/merge-ready

#67 add dynamic config disable configuration and fix zone allocations out of order
  cmd/katalyst-agent/app/options/global/metaserver.go
  pkg/config/agent/global/metaserver.go
  pkg/metaserver/metaserver.go
  pkg/util/cnr_topology.go
Labels: bug, workflow/merge-ready

#63 fix(sysadvisor): fix failed to find regions and pools
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
Labels: bug, workflow/merge-ready

#60 fix(sysadvisor): maximize share pool size when disable reclaim
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
Labels: bug, workflow/merge-ready

#66 fix(qrm): set sidecar owner pool name same to its main container
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/allocation_handlers.go
Labels: workflow/merge-ready

#68 memory headroom canonical policy support enable buffer
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/headroom/policy_base.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/headroom/policy_canonical.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/memory_advisor.go
  pkg/agent/resourcemanager/reporter/manager_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_buffer.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/headroom/policy_base.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/headroom/policy_canonical.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/memory_advisor.go
Labels: enhancement, workflow/merge-ready

#70 support to use transformed informer in lifecycle controller
  cmd/base/context.go
  cmd/base/options/generic.go
  pkg/config/generic/generic_base.go
  pkg/controller/lifecycle/cnr_eviction.go
  pkg/controller/spd/spd.go
  pkg/util/native/informer_dynamic.go
  pkg/util/native/informer_test.go
  pkg/util/native/informer_transformed.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#73 pod resources filter support pod parameter
  pkg/agent/resourcemanager/fetcher/kubelet/topology/podresourcesserver.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/podresourcesserver_test.go
Labels: Chore, workflow/merge-ready

#19 feat(qrm): support memory enhancement numa_exclusive
  cmd/base/options/qos.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/allocation_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/hint_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/allocation_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/hint_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
  pkg/config/generic/qos.go
  pkg/util/qos/mem_enhancement.go
Labels: enhancement, workflow/merge-ready

#75 fix(spd): fix nil reference
  pkg/metaserver/spd/checkpoint/checkpoint.go
Labels: bug, workflow/merge-ready

#76 fix meta server no start success
  pkg/metaserver/agent/pod/pod.go
  pkg/metaserver/metaserver.go
Labels: bug

#78 add pod fetcher health check
  pkg/metaserver/agent/pod/pod.go
  pkg/metaserver/external/manager.go
  pkg/metaserver/metaserver.go
  pkg/metaserver/metaserver_test.go
Labels: Chore, workflow/merge-ready

#81 skip retry update config when skip failed initialization enable
  pkg/metaserver/config/manager.go
Labels: Chore, workflow/need-review, workflow/merge-ready

#80 fix(qrm): ensures dedicated_cores owner pool non-empty
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/allocation_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
Labels: workflow/merge-ready

#79 feat(eviction): support dryrun plugin
  cmd/katalyst-agent/app/options/eviction/eviction_base.go
  pkg/agent/evictionmanager/eviction_resp_collector.go
  pkg/agent/evictionmanager/manager.go
  pkg/agent/evictionmanager/manager_test.go
  pkg/config/agent/eviction/eviciton_base.go
Labels: enhancement, workflow/merge-ready

#84 fix memory plugin ut for mac
  pkg/util/machine/topology.go
Labels: workflow/need-review, workflow/merge-ready
