Repository kubewharf/katalyst-core, pull requests merged in 2023-12, with the labels that each got.

#388 fix(spd): parseBaselineCoefficient returns error if BaselineCoefficient is empty
  go.mod
  go.sum
  pkg/controller/spd/spd.go
  pkg/controller/spd/spd_baseline.go
  pkg/controller/spd/spd_baseline_test.go
  pkg/controller/spd/spd_test.go
  pkg/util/spd.go
  pkg/util/spd_baseline.go
  pkg/util/spd_baseline_test.go
Labels: bug, workflow/merge-ready

#386 feat(kcmas): multiple index keys
  cmd/katalyst-metric/app/options/store.go
  pkg/config/metric/store.go
  pkg/custom-metric/provider/provider_test.go
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/cache_test.go
  pkg/custom-metric/store/local/local_store.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#392 fix(kcmas): missing store instance in same node
  pkg/util/service-discovery/service_single_port_sd.go
Labels: bug, workflow/need-review, workflow/merge-ready

#393 fix(spd): baseline checking
  pkg/util/spd_baseline.go
  pkg/util/spd_baseline_test.go
Labels: bug, workflow/merge-ready

#394 feat(qrm): adapt drop cache operation with cgv2
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
  pkg/util/cgroup/manager/cgroup.go
  pkg/util/cgroup/manager/cgroup_test.go
Labels: workflow/need-review

#397 suppression eviction add PodUniqKeyCmpFunc to make sure the sort result is stable
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go
  pkg/util/general/sorter.go
  pkg/util/native/pod_sorter.go
  pkg/util/native/pod_sorter_test.go
Labels: bug, workflow/need-review

#401 feat(qrm): support getting specified pool name in QoS conf
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util_test.go
  pkg/config/generic/qos.go
Labels: workflow/need-review, workflow/merge-ready

#404 enhancement(eviction): set skip pools via conf
  cmd/katalyst-agent/app/options/qrm/cpu_plugin.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go
  pkg/config/agent/qrm/cpu_plugin.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#398 feat(util): add interface Empty() to determine whether samples should…
  pkg/util/general/window.go
  pkg/util/general/window_test.go
Labels: enhancement, workflow/merge-ready

#399 Removing duplicated logging
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/model/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
  pkg/consts/metric.go
Labels: workflow/merge-ready

#407 fix(qrm): use phase pending instead of active to judge if need to ramp up
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
  pkg/util/native/pods.go
  pkg/util/native/pods_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#408 fix(spd): fix deadlock
  pkg/controller/spd/indicator-plugin/manager.go
Labels: bug, workflow/merge-ready

#409 feat(advisor): enable borwein result fetcher independently
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
Labels: workflow/merge-ready

#410 support report numa count to kcnr
  pkg/agent/resourcemanager/fetcher/system/systemplugin.go
Labels: chore, workflow/need-review, workflow/merge-ready

#411 Fix/deadlock
  pkg/controller/spd/indicator-plugin/manager.go
Labels: bug, workflow/need-review

#412 feat(advisor): add some metrics for borwein model result fetcher
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
Labels: workflow/need-review, workflow/merge-ready

#413 support report numa count to kcnr
  pkg/agent/resourcemanager/fetcher/system/systemplugin.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#405 isolation support non-exclusive
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
  pkg/agent/sysadvisor/plugin/qosaware/qos_aware.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_load.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go
  pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/server.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_isolation.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#416 add timestamp to get feature function
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go
Labels: workflow/merge-ready

#415 enhancement(sysadvisor): introduce minCriticalWatermark to determin m…
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go
Labels: enhancement, workflow/merge-ready

#424 report ratio of overload container
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
Labels: workflow/merge-ready

#425 feat(advisor): add indicator offset metric for borwein controller
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go
Labels: workflow/need-review

#426 fix race conditions for malachite
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod_test.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
Labels: bug, workflow/need-review, workflow/merge-ready

#427 add locking framework to detect potential deadlocks
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/util/syntax/lock.go
  pkg/util/syntax/lock_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready
