Repository kubewharf/katalyst-core, pull requests merged in 2023-04, with the labels that each got.

#11 chore(*): add codecov checks and pr comments
  .github/workflows/ci.yml
  Makefile
  codecov.yml
Labels: Chore

#2 fix(*): fix doc and memory QRM plugin
  .github/workflows/ci.yml
  README.md
  codecov.yml
  docs/imgs/custom-metrics-monolith-mode.jpg
  docs/imgs/custom-metrics-multi-store-mode.jpg
  docs/imgs/custom-metrics-overview.jpg
  docs/imgs/custom-metrics-sharding-mode.jpg
  docs/imgs/eviction-manager-overview.png
  docs/imgs/qrm-design-overview.png
  docs/imgs/qrm-detailed-working-flow.png
  docs/imgs/reporter-manager-overview.jpg
  docs/imgs/scheduler-balanced-plugin.jpg
  docs/imgs/scheduler-fit-plugin.jpg
  docs/imgs/scheduler-overall-arch.jpg
  docs/proposals/metric/20221202-katalyst-custom-metrics-apiserver.md
  docs/proposals/qos-management/eviction-manager/20220424-eviction-manager.md
  docs/proposals/qos-management/qos-resource-manager/20221018-qos-resource-manager.md
  docs/proposals/qos-management/reporter-manager/20220515-reporter-manager.md
  docs/proposals/qos-management/wip-20220615-sys-advisor.md
  docs/proposals/qos-management/wip-20220706-dynamic-configuration.md
  docs/proposals/scheduling/20220913-katalyst-scheduler-design.md
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
Labels: bug

#13 feat(sysadvisor): choose effective headroom and provison policy by co…
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/memory_advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/memory_advisor.go
Labels: enhancement

#16 chore(*): add templates for pull requests and issues
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Chore

#25 refine implementation of sysadvisor policies
  pkg/agent/sysadvisor/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
Labels: style

#28 chore(*): modify the threshold of codecov
  codecov.yml
Labels: Chore

#26 fix(qrm_sysadvisor): ensure directories of qrm sysadvisor communication socks existing before listening them
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server.go
  pkg/util/cgroup/manager/v2/fs_linux.go
Labels: bug, workflow/merge-ready

#34 fix(sysadvisor): fix deadlock
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
Labels: bug, workflow/need-review

#20 add node name label for pod metric in kcmas
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
Labels: enhancement, workflow/merge-ready

#35 fix(sysadvisor): not clear binding numas any more
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
Labels: bug, workflow/merge-ready

#32 refactor(sysadvisor): headroom manager remove broker
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/reporter/headroom_reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/broker/broker.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/cpu.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic_test.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/memory.go
  pkg/config/agent/sysadvisor/qosaware/reporter/headroom_reporter.go
Labels: Chore, workflow/merge-ready

#36 fix(sysadvisor): fix undercounting of headroom without dedicated_core…
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
Labels: bug, workflow/merge-ready

#44 add util to read file into string slices
  pkg/util/general/file.go
  pkg/util/general/file_test.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#37 fix(sysadvisor): fix create duplicated regions for distinct container…
  pkg/agent/sysadvisor/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu/cpu_server_test.go
  pkg/agent/sysadvisor/types/helper.go
  pkg/agent/sysadvisor/types/types.go
Labels: bug, workflow/merge-ready

#38 refactor(sysadvisor): emit metrics even when reclaim disabled
  pkg/agent/sysadvisor/plugin/qosaware/reporter/manager/resource/generic.go
Labels: Chore, workflow/merge-ready

#40 refactor(qosaware): refine estimate resource usage
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
Labels: enhancement, workflow/merge-ready

#39 feat(metaserver): support get pod by uid
  pkg/metaserver/agent/agent_test.go
  pkg/metaserver/agent/pod/pod.go
  pkg/metaserver/agent/pod/pod_stub.go
  pkg/metaserver/agent/pod/runtime.go
Labels: enhancement, workflow/merge-ready

#41 chore(*): add pr status check to CI pipeline
  .github/workflows/status-check.yml
Labels: Chore, workflow/need-review, workflow/merge-ready
