Repository kubewharf/katalyst-core, pull requests merged in 2024-10, with the labels that each got.

#702 Refactor the QRM plugin state
  cmd/katalyst-agent/app/options/qrm/cpu_plugin.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/plugins/numa_balancer.go
  pkg/agent/qrm-plugins/commonstate/pool.go
  pkg/agent/qrm-plugins/commonstate/state.go
  pkg/agent/qrm-plugins/commonstate/util.go
  pkg/agent/qrm-plugins/commonstate/util_test.go
  pkg/agent/qrm-plugins/commonstate/utils.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpuadvisor/helper.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_metric.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/util_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/validator/validator_cpu_advisor.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/vpa_test.go
  pkg/agent/qrm-plugins/cpu/nativepolicy/policy.go
  pkg/agent/qrm-plugins/cpu/nativepolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/cpu/util/util_test.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_async_handler.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/state/state.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/state/util.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_load.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/isolation/isolator_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/memory_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/cache_reaper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/policy/policy_canonical_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
  pkg/config/generic/qos.go
Labels: chore

#694 feat: report NUMA cpu usage
  pkg/agent/evictionmanager/plugin/memory/numa_pressure_test.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/cache_reaper.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/agent/metric/helper/container.go
  pkg/metaserver/agent/metric/metric_impl.go
  pkg/metaserver/agent/metric/metric_test.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
  pkg/metaserver/agent/metric/provisioner/malachite/types/cgroupv1.go
  pkg/metaserver/agent/metric/provisioner/malachite/types/cgroupv2.go
  pkg/metaserver/agent/metric/provisioner/rodan/provisioner.go
  pkg/metaserver/agent/metric/provisioner/rodan/provisioner_test.go
  pkg/metaserver/agent/metric/types/metric.go
  pkg/util/metric/store.go
  pkg/util/metric/store_util.go
Labels: enhancement, workflow/need-review

#685 refactor: make kernel allocate zram memory at allowed NUMAs of workload process
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_offloading.go
  pkg/util/cgroup/manager/cgroup.go
  pkg/util/cgroup/manager/cgroup_test.go
Labels: enhancement, workflow/need-review

#667 feat(fragmem): unified solution for memory compaction
  cmd/katalyst-agent/app/options/qrm/memory_plugin.go
  pkg/agent/qrm-plugins/memory/consts/consts.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/handlers/fragmem/const.go
  pkg/agent/qrm-plugins/memory/handlers/fragmem/fragmem_linux.go
  pkg/agent/qrm-plugins/memory/handlers/fragmem/fragmem_linux_test.go
  pkg/agent/qrm-plugins/memory/handlers/fragmem/fragmem_unsupported.go
  pkg/agent/qrm-plugins/memory/handlers/fragmem/utils_linux.go
  pkg/config/agent/qrm/memory_plugin.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
  pkg/metaserver/agent/metric/provisioner/malachite/types/system.go
  pkg/util/process/system.go
  pkg/util/process/system_test.go
Labels: workflow/need-review

#684 refactor resource-recommend controller
  cmd/katalyst-controller/app/controller/resourcerecommender.go
  cmd/katalyst-controller/app/options/resourcerecommender.go
  go.mod
  go.sum
  pkg/client/control/resourcerecommend.go
  pkg/client/control/resourcerecommend_test.go
  pkg/config/controller/resourcerecommender.go
  pkg/controller/resource-recommend/controller/controller.go
  pkg/controller/resource-recommend/controller/controller_test.go
  pkg/controller/resource-recommend/controller/oom_recorder_controller.go
  pkg/controller/resource-recommend/controller/oom_recorder_controller_test.go
  pkg/controller/resource-recommend/controller/resourcerecommend_controller.go
  pkg/controller/resource-recommend/controller/resourcerecommend_controller_test.go
  pkg/controller/resource-recommend/oom/oom_recorder.go
  pkg/controller/resource-recommend/oom/oom_recorder_test.go
  pkg/controller/resource-recommend/processor/manager/processor_manager.go
  pkg/controller/resource-recommend/processor/percentile/process_gc.go
  pkg/controller/resource-recommend/processor/percentile/process_gc_test.go
  pkg/controller/resource-recommend/processor/percentile/processor.go
  pkg/util/resource-recommend/resource/k8s_resource.go
  pkg/util/resource-recommend/resource/k8s_resource_test.go
  pkg/util/resource-recommend/resource/k8s_resource_test_util.go
  pkg/util/resource-recommend/types/conditions/conditions_test.go
  pkg/util/resource-recommend/types/recommendation/recommendation.go
  pkg/util/resource-recommend/types/recommendation/recommendation_test.go
  pkg/util/resource-recommend/types/recommendation/validate.go
  pkg/util/resource-recommend/types/recommendation/validate_test.go
Labels: workflow/merge-ready
