Repository kubewharf/katalyst-core, pull requests merged in 2024-08, with the labels that each got.

#666 support clear residual net class
  pkg/agent/qrm-plugins/network/staticpolicy/policy.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go
  pkg/metaserver/external/cgroupid/manager.go
  pkg/util/external/network/manager.go
  pkg/util/external/network/manager_linux.go
  pkg/util/external/network/manager_unsupported.go
Labels: bug, workflow/need-review

#673 fix: fix some orm and reporter plugin issues
  cmd/katalyst-agent/app/agent/orm.go
  cmd/katalyst-agent/app/options/orm/orm_base.go
  cmd/katalyst-agent/app/options/reporter/kubelet_plugin.go
  pkg/agent/orm/manager.go
  pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go
  pkg/config/agent/orm/orm_base.go
  pkg/config/agent/reporter/kubelet_plugin.go
Labels: workflow/need-review

#674 fix(reporter): fix race condition regarding orm and reporter start order
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go
  pkg/util/general/file.go
  pkg/util/kubelet/podresources/client.go
Labels: bug, workflow/need-review

#671 feat(qrm): refine getting hint by memory bandwidth
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
Labels: refactor

#659 feat: support to update reservedForReclaim dynamicly
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_load.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/util/machine/cpu.go
  pkg/util/machine/cpu_test.go
Labels: enhancement, workflow/need-review
