Repository kubewharf/katalyst-core, pull requests merged in 2024-04, with the labels that each got.

#499 refactor(sysadvisor): refine memory guard
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/agent/metric/metric_impl.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/types/metric.go
  pkg/util/metric/store.go
Labels: enhancement, workflow/need-review

#530 feat(kcmas): enable grouped aggregate metric
  go.mod
  go.sum
  pkg/custom-metric/provider/provider_test.go
  pkg/custom-metric/provider/util.go
  pkg/custom-metric/store/data/cache.go
  pkg/custom-metric/store/data/cache_test.go
  pkg/custom-metric/store/data/internal/internal.go
  pkg/custom-metric/store/data/types/aggragated.go
  pkg/custom-metric/store/data/types/metric.go
  pkg/custom-metric/store/remote/remote_store.go
Labels: enhancement, workflow/merge-ready

#532 reduce the frequency of spd manager try to get unused spd from remote api-server
  pkg/metaserver/spd/cache.go
  pkg/metaserver/spd/fetcher.go
Labels: bug, chore

#520 feat(sysadvisor): add healthz check
  pkg/agent/evictionmanager/conditions.go
  pkg/agent/evictionmanager/manager.go
  pkg/agent/evictionmanager/manager_test.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure.go
  pkg/agent/resourcemanager/fetcher/manager.go
  pkg/agent/resourcemanager/fetcher/manager_healthz.go
  pkg/agent/resourcemanager/fetcher/manager_test.go
  pkg/agent/sysadvisor/plugin/inference/inference.go
  pkg/agent/sysadvisor/plugin/metacache/metacache.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/headroom_reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/reporter_interface.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/pod/pod.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#539 chore(sysadvisor): disable some healthcheck rule
  pkg/agent/sysadvisor/plugin/inference/inference.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/reporter_interface.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go
Labels: enhancement, workflow/need-review

#543 chore(sysadvisor): refine some healthcheck rule
  pkg/agent/resourcemanager/fetcher/manager.go
  pkg/agent/resourcemanager/fetcher/manager_test.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/headroom_reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/metaserver/metaserver_test.go
Labels: workflow/need-review, workflow/merge-ready

#536 refactor(sysadvisor): support dynamic enable memory guard
  cmd/katalyst-agent/app/options/dynamic/adminqos/adminqos_base.go
  cmd/katalyst-agent/app/options/dynamic/adminqos/advisor/advisor_base.go
  cmd/katalyst-agent/app/options/dynamic/adminqos/advisor/memory_guard.go
  go.mod
  go.sum
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_guard.go
  pkg/config/agent/dynamic/adminqos/adminqos_base.go
  pkg/config/agent/dynamic/adminqos/advisor/advisor_base.go
  pkg/config/agent/dynamic/adminqos/advisor/memory_guard.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/agent/metric/metric_impl.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/types/metric.go
  pkg/util/metric/store.go
Labels: enhancement, workflow/need-review

#552 add codecov uploading secret tokens
  .github/workflows/ci.yml
Labels: workflow/merge-ready

#546 feat(qrm): add ResourceAnnotationKeyNICNetNSName
  go.mod
  go.sum
  pkg/agent/qrm-plugins/network/staticpolicy/policy.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy_test.go
Labels: chore, workflow/merge-ready

#453 feat(ORM): add orm podResources server
  cmd/katalyst-agent/app/agent/orm.go
  cmd/katalyst-agent/app/options/orm/orm_base.go
  go.mod
  pkg/agent/orm/deviceprovider/kubelet/provider.go
  pkg/agent/orm/deviceprovider/kubelet/provider_test.go
  pkg/agent/orm/endpoint/endpoint.go
  pkg/agent/orm/endpoint/endpoint_test.go
  pkg/agent/orm/endpoint/resource_plugin_stub.go
  pkg/agent/orm/manager.go
  pkg/agent/orm/manager_test.go
  pkg/agent/orm/metamanager/manager.go
  pkg/agent/orm/metamanager/manager_test.go
  pkg/agent/orm/resourceprovider.go
  pkg/agent/orm/resourceprovider_test.go
  pkg/agent/orm/server/podresources/server_v1.go
  pkg/agent/orm/server/podresources/server_v1_test.go
  pkg/agent/orm/server/podresources/testing/provider_mock.go
  pkg/agent/orm/server/podresources/types.go
  pkg/agent/orm/server/server.go
  pkg/agent/orm/types.go
  pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go
  pkg/config/agent/orm/orm_base.go
  pkg/util/kubelet/podresources/client.go
Labels: enhancement, workflow/need-review

#555 cherry pick of #541: feat(reporter): validate specific resources in pod resources response
  .github/workflows/ci.yml
  cmd/katalyst-agent/app/options/reporter/kubelet_plugin.go
  pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go
  pkg/config/agent/reporter/kubelet_plugin.go
Labels: enhancement, workflow/need-review

#557 fix MergeAttributes sort zone attribute
  pkg/util/cnr.go
Labels: bug, workflow/merge-ready

#525 doc(*): add proposal for enhance orm by nri
  docs/proposals/qos-management/orm-nri/20240303-orm-nri.md
  docs/proposals/qos-management/orm-nri/kubernetes-enhance-overview.png
  docs/proposals/qos-management/orm-nri/nri-architecture.png
  docs/proposals/qos-management/orm-nri/orm-architecture.png
  docs/proposals/qos-management/orm-nri/orm-nir-details.png
Labels: enhancement, workflow/need-review, workflow/merge-ready

#469 feat(metric): add rodan metric provisioner
  cmd/katalyst-agent/app/options/metaserver/metaserver.go
  pkg/config/agent/metaserver/agent.go
  pkg/metaserver/agent/metric/metric_impl.go
  pkg/metaserver/agent/metric/metric_provisoner.go
  pkg/metaserver/agent/metric/provisioner/cgroup/provisioner.go
  pkg/metaserver/agent/metric/provisioner/kubelet/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
  pkg/metaserver/agent/metric/provisioner/rodan/client/client.go
  pkg/metaserver/agent/metric/provisioner/rodan/client/client_node.go
  pkg/metaserver/agent/metric/provisioner/rodan/client/client_node_test.go
  pkg/metaserver/agent/metric/provisioner/rodan/client/client_pod.go
  pkg/metaserver/agent/metric/provisioner/rodan/client/client_pod_test.go
  pkg/metaserver/agent/metric/provisioner/rodan/provisioner.go
  pkg/metaserver/agent/metric/provisioner/rodan/provisioner_test.go
  pkg/metaserver/agent/metric/provisioner/rodan/types/consts.go
  pkg/metaserver/agent/metric/provisioner/rodan/types/types.go
  pkg/metaserver/agent/metric/provisioner/rodan/types/types_test.go
Labels: enhancement, workflow/need-review

#472 feat(overcommit): add realtime overcommit advisor plugin
  cmd/base/context_fake.go
  cmd/katalyst-agent/app/options/sysadvisor/overcommit/overcommit_aware_plugin.go
  cmd/katalyst-agent/app/options/sysadvisor/overcommit/realtime/realtime.go
  cmd/katalyst-agent/app/options/sysadvisor/sysadvisor_base.go
  cmd/katalyst-scheduler/app/server.go
  cmd/katalyst-scheduler/main.go
  go.mod
  go.sum
  pkg/agent/sysadvisor/plugin/overcommitmentaware/overcommitment_aware.go
  pkg/agent/sysadvisor/plugin/overcommitmentaware/realtime/realtime.go
  pkg/agent/sysadvisor/plugin/overcommitmentaware/realtime/realtime_test.go
  pkg/agent/sysadvisor/plugin/overcommitmentaware/reporter/reporter.go
  pkg/agent/sysadvisor/plugin/overcommitmentaware/reporter/reporter_test.go
  pkg/agent/sysadvisor/sysadvisor.go
  pkg/agent/sysadvisor/types/types.go
  pkg/config/agent/sysadvisor/overcommit/overcommit_aware_plugin.go
  pkg/config/agent/sysadvisor/overcommit/realtime/realtime.go
  pkg/config/agent/sysadvisor/sysadvisor_base.go
  pkg/controller/overcommit/node/handler.go
  pkg/controller/overcommit/node/node.go
  pkg/controller/overcommit/node/node_test.go
  pkg/scheduler/cache/nodeinfo.go
  pkg/scheduler/eventhandlers/cnr_handler.go
  pkg/scheduler/eventhandlers/handler.go
  pkg/scheduler/eventhandlers/pod_handler.go
  pkg/scheduler/plugins/nodeovercommitment/cache/cache.go
  pkg/scheduler/plugins/nodeovercommitment/cache/handler.go
  pkg/scheduler/plugins/nodeovercommitment/fit.go
  pkg/scheduler/plugins/nodeovercommitment/fit_test.go
  pkg/scheduler/plugins/nodeovercommitment/plugin.go
  pkg/scheduler/plugins/nodeovercommitment/plugin_test.go
  pkg/scheduler/plugins/nodeovercommitment/reserve.go
  pkg/scheduler/plugins/nodeovercommitment/reserve_test.go
  pkg/scheduler/plugins/noderesourcetopology/plugin.go
  pkg/scheduler/plugins/qosawarenoderesources/balanced_allocation.go
  pkg/scheduler/plugins/qosawarenoderesources/fit.go
  pkg/util/cnr.go
  pkg/util/native/pod_resource.go
  pkg/util/native/resources_test.go
  pkg/util/overcommit/overcommit.go
  pkg/webhook/mutating/node/allocatable_mutator.go
  pkg/webhook/mutating/node/node_test.go
Labels: enhancement, workflow/need-review

#562 chore(*): release v0.5.0
  go.mod
  go.sum
Labels: chore, workflow/need-review, workflow/merge-ready

#549 feat: Add TransparentMemoryOffloading plugin to trigger memory offloading
  cmd/katalyst-agent/app/options/dynamic/dynamic_base.go
  cmd/katalyst-agent/app/options/dynamic/tmo/tmo_base.go
  cmd/katalyst-agent/app/options/dynamic/tmo/tmodefault/tmo_default_config.go
  cmd/katalyst-agent/app/options/global/base.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/const.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/util/consts.go
  pkg/agent/qrm-plugins/util/util.go
  pkg/agent/sysadvisor/plugin/qosaware/qos_aware.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_offloading.go
  pkg/config/agent/dynamic/crd/dynamic_crd.go
  pkg/config/agent/dynamic/dynamic_base.go
  pkg/config/agent/dynamic/tmo/tmo_base.go
  pkg/config/agent/global/base.go
  pkg/consts/common.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/types/common.go
  pkg/util/cgroup/common/types.go
  pkg/util/cgroup/manager/cgroup.go
  pkg/util/cgroup/manager/cgroup_test.go
  pkg/util/cgroup/manager/v1/fs_linux.go
  pkg/util/cgroup/manager/v2/fs_linux.go
  pkg/util/general/common.go
  pkg/util/metric/store.go
Labels: enhancement, workflow/need-review
