Repository kubewharf/katalyst-core, pull requests merged in 2024-01, with the labels that each got.

#428 fix container metrics
  cmd/katalyst-agent/app/options/sysadvisor/inference/inference_plugin.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
Labels: workflow/merge-ready

#423 add model ouput to kcmas
  pkg/agent/sysadvisor/plugin/inference/inference.go
  pkg/agent/sysadvisor/plugin/inference/inference_test.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go
  pkg/agent/sysadvisor/plugin/inference/models/borwein/types/types.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/model.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go
  pkg/metaserver/agent/metric/malachite/fetcher.go
  pkg/metaserver/agent/metric/malachite/fetcher_calculate.go
Labels: workflow/merge-ready

#437 chore(*): release v0.4.0
  go.mod
  go.sum
Labels: chore

#440 fix(qrm): fix panic when handleAdvisorCPUSetMems got nil allocationInfo, add robustness
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
Labels: bug, workflow/need-review

#441 add logs
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_dedicated.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
Labels: enhancement, workflow/merge-ready

#442 remove orm from /agent/resourcemanager into /agent
  cmd/katalyst-agent/app/agent/orm.go
  pkg/agent/orm/checkpoint.go
  pkg/agent/orm/checkpoint/checkpoint.go
  pkg/agent/orm/checkpoint/checkpoint_test.go
  pkg/agent/orm/checkpoint_test.go
  pkg/agent/orm/endpoint/consts.go
  pkg/agent/orm/endpoint/endpoint.go
  pkg/agent/orm/endpoint/endpoint_test.go
  pkg/agent/orm/endpoint/resource_plugin_stub.go
  pkg/agent/orm/executor/executor.go
  pkg/agent/orm/executor/executor_test.go
  pkg/agent/orm/manager.go
  pkg/agent/orm/manager_test.go
  pkg/agent/orm/metamanager/manager.go
  pkg/agent/orm/metamanager/manager_test.go
  pkg/agent/orm/metamanager/types.go
  pkg/agent/orm/pluginhandler.go
  pkg/agent/orm/pod_resource.go
  pkg/agent/orm/pod_resource_test.go
  pkg/agent/orm/types.go
Labels: chore, workflow/need-review

#439 fix reclaim pool entry of non binding numas in calculation result
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
Labels: bug, workflow/need-review

#438 bugfix: request summary from podsEndpoint when enable kubelet secure port
  pkg/metaserver/agent/metric/provisioner/kubelet/client/client.go
Labels: bug, workflow/need-review

#443 refactor(sysadvisor): consider per numa memory reserved
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_numa_aware_test.go
Labels: enhancement, workflow/need-review

#444 refine the implementation for qos configurations
  cmd/base/options/qos.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_test.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy.go
  pkg/agent/qrm-plugins/util/util.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein_test.go
  pkg/config/generic/qos.go
  pkg/config/generic/qos_expander.go
  pkg/controller/spd/spd.go
  pkg/scheduler/util/qos.go
  pkg/util/qos/cpu_enhancement.go
  pkg/util/qos/helper/enhancement_helper.go
  pkg/util/qos/helper/qos_helper.go
  pkg/util/qos/mem_enhancement.go
Labels: workflow/need-review, workflow/merge-ready

#446 fix(metric): numa memory stats
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
Labels: bug, workflow/merge-ready

#450 refactor(eviction): support to config eviciton tolerance duration
  cmd/katalyst-agent/app/options/dynamic/adminqos/eviction/reclaimed_resources_eviction.go
  go.mod
  go.sum
  pkg/agent/evictionmanager/plugin/resource/reclaimed_resources.go
  pkg/agent/evictionmanager/plugin/resource/resources.go
  pkg/config/agent/dynamic/adminqos/eviction/reclaimed_resources_eviction.go
  pkg/controller/lifecycle/agent-healthz/helper/taint_cnr.go
Labels: enhancement, workflow/merge-ready

#455 fix eviction manager grpc connection leak
  pkg/agent/evictionmanager/manager.go
Labels: bug, workflow/need-review, workflow/merge-ready

#458 feat(async_work): add async work duration and panic metrics
  pkg/util/asyncworker/async_workers.go
  pkg/util/asyncworker/helpers.go
  pkg/util/asyncworker/types.go
Labels: workflow/need-review, workflow/merge-ready

#463 refactor(sysadvisor): add metric and tag
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/provisioner/policy/policy_canonical.go
Labels: enhancement, workflow/merge-ready
