Repository kubewharf/katalyst-core, pull requests merged in 2024-05, with the labels that each got.

#544 fix sibling numa set
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go
  pkg/util/machine/topology.go
  pkg/util/machine/topology_linux.go
  pkg/util/machine/topology_test.go
Labels: bug, workflow/need-review

#573 kubelet plugin run add fatal error
  pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin.go
Labels: chore

#585 fix: ignore not existed cgroup paths
  cmd/katalyst-agent/app/options/global/base.go
  pkg/config/agent/global/base.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
Labels: enhancement, workflow/merge-ready

#586 bugfix: fix resource leakage caused by the duplicate sample of rodan …
  pkg/metaserver/agent/metric/provisioner/rodan/provisioner.go
  pkg/metaserver/agent/metric/provisioner/rodan/provisioner_test.go
Labels: bug, workflow/need-review

#567 remote reporter plugin and topology adapter support context timeout
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter.go
  pkg/agent/resourcemanager/fetcher/plugin/endpoint.go
  pkg/agent/sysadvisor/plugin/overcommitmentaware/reporter/reporter.go
Labels: workflow/need-review

#588 fix: convert memory by quantity.Value in overcommit controller
  pkg/controller/overcommit/node/node.go
  pkg/controller/overcommit/node/node_test.go
  pkg/util/native/resources.go
Labels: bug, workflow/need-review
