Repository kubewharf/katalyst-core, pull requests merged in 2024-09, with the labels that each got.

#691 fix(*): adapt to kubelet configz endpoint changes to support K8s 1.28
  pkg/agent/resourcemanager/fetcher/kubelet/kubeletplugin_test.go
  pkg/agent/resourcemanager/fetcher/kubelet/topology/topology_adapter_test.go
  pkg/agent/sysadvisor/plugin/overcommitmentaware/realtime/realtime_test.go
  pkg/agent/sysadvisor/plugin/overcommitmentaware/reporter/reporter_test.go
  pkg/metaserver/agent/agent_test.go
  pkg/metaserver/agent/kubeletconfig/fake_kubeletconfig.go
  pkg/metaserver/agent/kubeletconfig/kubeletconfig.go
  pkg/util/kubelet/config/kubeletconfig.go
  pkg/util/kubelet/config/kubeletconfig_test.go
  pkg/util/native/kubelet.go
  pkg/util/native/kubelet_test.go
Labels: bug, workflow/need-review, workflow/merge-ready

#682 reduce move_pages granularity
  pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go
Labels: enhancement, workflow/merge-ready

#690 fix: check having upper bound
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/util/machine/zone.go
  pkg/util/machine/zone_linux.go
Labels: bug, workflow/merge-ready

#693 feat(tmo): block config support kcc and optimize target size calc
  go.mod
  go.sum
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_offloading.go
  pkg/config/agent/dynamic/tmo/tmo_base.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
Labels: enhancement, workflow/merge-ready

#669 dirtymem: adding support to virtio disk
  cmd/katalyst-agent/app/options/qrm/io_plugin.go
  pkg/agent/qrm-plugins/io/handlers/dirtymem/dirtymem_linux_test.go
  pkg/agent/qrm-plugins/io/handlers/dirtymem/wbt_linux.go
  pkg/config/agent/qrm/io_plugin.go
  pkg/consts/common.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
Labels: workflow/need-review
