Repository kubewharf/katalyst-core, pull requests merged in 2024-06, with the labels that each got.

#605 refactor(async): support limited async workers
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
  pkg/util/asyncworker/async_limited_workers.go
  pkg/util/asyncworker/async_workers_test.go
  pkg/util/asyncworker/types.go
Labels: enhancement, workflow/need-review

#572 feat(general): audit manager framework
  cmd/katalyst-agent/app/agent/audit.go
  cmd/katalyst-agent/app/enableagents.go
  cmd/katalyst-agent/app/options/global/audit.go
  cmd/katalyst-agent/app/options/options.go
  pkg/agent/audit/manager.go
  pkg/agent/audit/manager_test.go
  pkg/agent/audit/sink/basesink.go
  pkg/agent/audit/sink/logbased.go
  pkg/agent/audit/sink/types.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go
  pkg/config/agent/agent_base.go
  pkg/config/agent/global/audit.go
  pkg/consts/common.go
  pkg/util/cgroup/common/cgroup_linux.go
  pkg/util/cgroup/common/types.go
  pkg/util/cgroup/manager/cgroup.go
  pkg/util/cgroup/manager/v1/fs_linux.go
  pkg/util/cgroup/manager/v2/fs_linux.go
  pkg/util/eventbus/event_bus.go
  pkg/util/eventbus/event_bus_test.go
  pkg/util/eventbus/types.go
Labels: enhancement, workflow/need-review

#614 feat(agent): refactor eviction/reporter healthz rule
  pkg/agent/evictionmanager/manager.go
  pkg/agent/evictionmanager/plugin/memory/helper.go
  pkg/agent/evictionmanager/plugin/memory/numa_pressure.go
  pkg/agent/evictionmanager/plugin/memory/system_pressure.go
  pkg/agent/evictionmanager/plugin/resource/resources.go
  pkg/agent/resourcemanager/fetcher/manager.go
Labels: workflow/need-review

#599 refine and fix checkLabelSelectorOverlap
  pkg/controller/kcc/kcct.go
  pkg/controller/kcc/kcct_test.go
Labels: bug, workflow/need-review

#612 refine GetSiblingNumaInfo
  cmd/katalyst-agent/app/options/global/base.go
  pkg/config/agent/global/base.go
  pkg/util/machine/topology.go
  pkg/util/machine/topology_test.go
Labels: enhancement, workflow/need-review

#619 fix(util): fix deadlock
  pkg/util/asyncworker/async_limited_workers.go
Labels: bug, workflow/need-review

#615 feat(lifecycle): emitter cluster health rate
  pkg/controller/lifecycle/agent-healthz/helper/healthz_check.go
Labels: enhancement, workflow/need-review

#613 feat(audit): eventbus metrics
  cmd/katalyst-agent/app/agent/audit.go
  pkg/util/eventbus/event_bus.go
  pkg/util/eventbus/event_bus_test.go
Labels: enhancement, workflow/need-review

#621 feat(lifecycle): emitter cluster health rate
  pkg/controller/lifecycle/agent-healthz/helper/healthz_check.go
Labels: workflow/need-review, workflow/merge-ready

#634 fix spd cache clear when checkpoint deleted
  pkg/metaserver/spd/cache.go
Labels: bug, workflow/need-review

#637 Compatible with spd with empty scope
  pkg/controller/spd/spd_indicator.go
Labels: bug, workflow/need-review
