Repository kubewharf/katalyst-core, pull requests merged in 2024-02, with the labels that each got.

#468 refactor(sysadvisor): add idle status for region
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
Labels: enhancement, workflow/merge-ready

#475 chore(agent): monitor agent start
  cmd/katalyst-agent/app/agent.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#429 feat(sysadvisor): support numa memory balance
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/plugins/common.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/memory/plugins/numa_balancer.go
  cmd/katalyst-agent/app/options/util/vendor_aware.go
  go.mod
  go.sum
  pkg/agent/qrm-plugins/memory/dynamicpolicy/memoryadvisor/const.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/util/consts.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go
  pkg/agent/sysadvisor/types/memory.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/plugins/common.go
  pkg/config/agent/sysadvisor/qosaware/resource/memory/plugins/numa_balancer.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/types/system.go
  pkg/util/asyncworker/async_workers.go
  pkg/util/asyncworker/async_workers_test.go
  pkg/util/asyncworker/types.go
  pkg/util/cgroup/common/cgroup_linux.go
  pkg/util/cgroup/common/types.go
  pkg/util/cgroup/manager/fake_manager.go
  pkg/util/cgroup/manager/manager.go
  pkg/util/cgroup/manager/v1/fs_linux.go
  pkg/util/cgroup/manager/v1/fs_unsupported.go
  pkg/util/cgroup/manager/v2/fs_linux.go
  pkg/util/cgroup/manager/v2/fs_unsupported.go
  pkg/util/machine/machine.go
  pkg/util/machine/machine_linux.go
  pkg/util/machine/topology.go
  pkg/util/machine/topology_linux.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#474 feat: support node metrics reporter
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/qos_aware_plugin.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/reporter/node_metric_reporter.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/reporter/reporter.go
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter_test.go
  pkg/agent/sysadvisor/plugin/qosaware/qos_aware.go
  pkg/agent/sysadvisor/plugin/qosaware/qos_aware_test.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/headroom_reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/headroom_reporter_test.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter_test.go
  pkg/agent/sysadvisor/plugin/qosaware/reporter/reporter_interface.go
  pkg/agent/sysadvisor/types/reporter.go
  pkg/config/agent/sysadvisor/qosaware/qos_aware_plugin.go
  pkg/config/agent/sysadvisor/qosaware/reporter/node_metric_reporter.go
  pkg/config/agent/sysadvisor/qosaware/reporter/reporter.go
  pkg/util/cnr.go
  pkg/util/syntax/reflect.go
Labels: enhancement, workflow/merge-ready

#445 refine(qrm): calculate pool size with much accuracy
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_advisor_handler.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_hint_handlers.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/state_test.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/state/util.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/util.go
  pkg/agent/qrm-plugins/cpu/nativepolicy/policy.go
  pkg/agent/qrm-plugins/cpu/nativepolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/cpu/nativepolicy/policy_hint_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_hint_handlers.go
  pkg/agent/qrm-plugins/network/staticpolicy/policy.go
  pkg/agent/qrm-plugins/util/util.go
  pkg/agent/qrm-plugins/util/util_test.go
Labels: workflow/need-review, workflow/merge-ready

#478 add cgroup metric fetcher in metaserver
  cmd/katalyst-agent/app/options/metaserver/metaserver.go
  pkg/agent/orm/endpoint/endpoint.go
  pkg/config/agent/metaserver/agent.go
  pkg/metaserver/agent/metric/fake_metric.go
  pkg/metaserver/agent/metric/metric_impl.go
  pkg/metaserver/agent/metric/metric_provisoner.go
  pkg/metaserver/agent/metric/provisioner/cgroup/provisioner.go
  pkg/metaserver/agent/metric/provisioner/kubelet/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
  pkg/metaserver/agent/metric/types/metric.go
Labels: enhancement, workflow/need-review, workflow/merge-ready
