Repository kubewharf/katalyst-core, pull requests merged in 2024-07, with the labels that each got.

#625 feat: support shared_cores overlap reclaimed_cores
  cmd/katalyst-agent/app/options/dynamic/adminqos/advisor/advisor_base.go
  cmd/katalyst-agent/app/options/dynamic/adminqos/advisor/cpu_provision.go
  cmd/katalyst-agent/app/options/dynamic/adminqos/advisor/cpu_region.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/provision/policy_base.go
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/region/cpu_share.go
  go.mod
  go.sum
  pkg/agent/sysadvisor/metacache/checkpoint_test.go
  pkg/agent/sysadvisor/plugin/inference/modelresultfetcher/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_util.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_dedicated.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_canonical_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_none.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/headroompolicy/policy_numa_exclusive_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_none.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_dedicated_numa_exclusive.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_isolation.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/regulator/regulator.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/helper.go
  pkg/agent/sysadvisor/types/cpu.go
  pkg/agent/sysadvisor/types/helper.go
  pkg/agent/sysadvisor/types/types.go
  pkg/config/agent/dynamic/adminqos/advisor/advisor_base.go
  pkg/config/agent/dynamic/adminqos/advisor/cpu_provision.go
  pkg/config/agent/dynamic/adminqos/advisor/cpu_region.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/cpu_advisor.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_base.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/region/cpu_share.go
  pkg/util/general/common.go
  pkg/util/general/deepcopy.go
Labels: enhancement, workflow/need-review

#641 fix: add flags
  cmd/katalyst-agent/app/options/dynamic/adminqos/advisor/cpu_provision.go
Labels: bug

#644 fix(advisor): fix reclaim overlap share cores
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/helper_test.go
Labels: bug, workflow/need-review

#553 Enhance ORM by nri
  cmd/katalyst-agent/app/options/orm/orm_base.go
  go.mod
  go.sum
  pkg/agent/orm/checkpoint_test.go
  pkg/agent/orm/manager.go
  pkg/agent/orm/manager_nri.go
  pkg/agent/orm/manager_nri_test.go
  pkg/agent/orm/manager_test.go
  pkg/agent/orm/pod_resource_test.go
  pkg/agent/sysadvisor/plugin/qosaware/server/base_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/cpu_server.go
  pkg/agent/sysadvisor/plugin/qosaware/server/memory_server.go
  pkg/config/agent/orm/orm_base.go
  pkg/consts/orm.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#606 agent get SPD syncly & spd creation improvement
  cmd/katalyst-agent/app/options/metaserver/metaserver.go
  pkg/config/agent/metaserver/spd.go
  pkg/controller/spd/indicator-plugin/manager.go
  pkg/controller/spd/indicator-plugin/plugin.go
  pkg/controller/spd/indicator-plugin/plugins/ihpa/plugin.go
  pkg/controller/spd/indicator-plugin/plugins/resource-portrait/indicator_plugin.go
  pkg/controller/spd/spd.go
  pkg/controller/spd/spd_indicator.go
  pkg/controller/spd/spd_test.go
  pkg/metaserver/spd/fetcher.go
  pkg/metaserver/spd/fetcher_test.go
  pkg/util/spd.go
Labels: enhancement, workflow/need-review

#649 chore(tmo): add more logs
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_offloading.go
Labels: enhancement, workflow/need-review

#651 spd fetcher add config for enable service profile namespaces
  cmd/katalyst-agent/app/options/metaserver/metaserver.go
  pkg/config/agent/metaserver/spd.go
  pkg/metaserver/spd/fetcher.go
Labels: workflow/need-review

#655 feat(qrm): remove dropcache when migrate numa memory
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
Labels: enhancement, workflow/need-review

#656 fix(sysadvisor): fix isolacted size calculated incorrectly
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common_test.go
Labels: bug, workflow/need-review

#663 refine pressure_supression eviction and getUtilBasedHeadroom
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/headroomassembler/assembler_common_util.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/estimation_canonical.go
  pkg/metaserver/agent/metric/helper/reclaim.go
Labels: enhancement, workflow/need-review
