Repository kubewharf/katalyst-core, pull requests merged in 2024-03, with the labels that each got.

#477 feat(qrm): use move_pages syscall to migrate numa memory
  go.mod
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/policy_allocation_handlers.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/util_linux_amd64_test.go
  pkg/agent/qrm-plugins/memory/dynamicpolicy/util_unsupported.go
Labels: workflow/need-review

#497 feat(meatserver): use multiple subsystems to detect cgroup path
  pkg/util/cgroup/common/path.go
  pkg/util/cgroup/common/types.go
Labels: bug, workflow/need-review, workflow/merge-ready

#501 chore(*): add logs
  pkg/agent/sysadvisor/plugin/qosaware/reporter/nodemetric_reporter.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/assembler/provisionassembler/assembler_common.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
Labels: enhancement, workflow/merge-ready

#503 feat(qrm): do evict and balance at the same time
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#490 customized plugin manager to skipping running if no handles and registered
  cmd/katalyst-agent/app/agent/context.go
Labels: bug, workflow/need-review, workflow/merge-ready

#506 fix(sysadvisor): numa balancer miss eviction
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go
Labels: bug

#507 add cnr reporter update cnr cost metrics and log
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
Labels: chore, workflow/need-review

#495 spd support extended indicator sdk and extended baseline
  go.mod
  go.sum
  pkg/controller/spd/indicator-plugin/manager.go
  pkg/controller/spd/indicator-plugin/plugin.go
  pkg/controller/spd/spd.go
  pkg/controller/spd/spd_baseline.go
  pkg/controller/spd/spd_baseline_test.go
  pkg/controller/spd/spd_indicator.go
  pkg/controller/spd/spd_test.go
  pkg/metaserver/spd/manager.go
  pkg/metaserver/spd/manager_test.go
  pkg/util/spd.go
  pkg/util/spd_baseline.go
  pkg/util/spd_baseline_test.go
  pkg/util/spd_test.go
Labels: workflow/need-review

#511 cnr reporter support merge siblings and machine info provide sibling numa info
  cmd/katalyst-agent/app/options/global/base.go
  pkg/config/agent/global/base.go
  pkg/util/cnr.go
  pkg/util/cnr_test.go
  pkg/util/machine/machine_linux.go
  pkg/util/machine/topology.go
  pkg/util/machine/topology_linux.go
Labels: enhancement, workflow/need-review

#512 renaming transformed logic for pod informer
  pkg/controller/lifecycle/agent-healthz/healthz_controller.go
  pkg/controller/spd/spd.go
  pkg/util/native/informer_test.go
  pkg/util/native/informer_transformed_pod.go
Labels: workflow/merge-ready

#513 fix(sysadvisor): get wrong max latency numa
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/plugin/memory_balancer.go
Labels: bug, workflow/merge-ready

#452 refactor(sysadvisor): make target indicator configurable
  cmd/katalyst-agent/app/options/sysadvisor/qosaware/resource/cpu/provision/policy_base.go
  go.mod
  go.sum
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/advisor_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_canonical_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/provisionpolicy/policy_rama_test.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_base.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/cpu/region/region_share.go
  pkg/agent/sysadvisor/types/cpu.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_base.go
  pkg/config/agent/sysadvisor/qosaware/resource/cpu/provision/policy_rama.go
Labels: enhancement, workflow/merge-ready

#508 fix invalid type transformation for BorweinInferenceResults
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein.go
  pkg/agent/sysadvisor/plugin/qosaware/resource/helper/modelctrl/borwein/borwein_test.go
Labels: workflow/merge-ready

#517 chore(*): add metrics and logs
  pkg/agent/resourcemanager/fetcher/manager.go
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
Labels: enhancement, workflow/need-review, workflow/merge-ready

#466 bugfix: marshal checkpoint by json
  pkg/agent/orm/checkpoint/checkpoint_test.go
  pkg/agent/orm/pod_resource.go
  pkg/agent/orm/pod_resource_test.go
Labels: bug, workflow/need-review

#521 chore(*): add metric
  pkg/agent/resourcemanager/fetcher/manager.go
Labels: enhancement, workflow/need-review

#522 spd: get qos Level by pod and its annotations
  pkg/controller/spd/spd.go
  pkg/controller/spd/spd_test.go
  pkg/util/native/object.go
Labels: bug, workflow/merge-ready

#524 skip memory estimation for reclaimed cores pod
  pkg/agent/sysadvisor/plugin/qosaware/resource/memory/headroompolicy/policy_canonical.go
Labels: chore, workflow/need-review
