Repository kubewharf/katalyst-core, pull requests merged in 2025-06, with the labels that each got.

#871 chore: support to set klog max size
  cmd/base/options/log.go
  pkg/util/general/log.go
Labels: workflow/merge-ready

#867 chore: add cgroupPath for reclaim metrics
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/cpueviction/strategy/pressure_suppression.go
  pkg/metaserver/agent/metric/helper/reclaim.go
Labels: enhancement, workflow/merge-ready

#865 feat: support malachite resctrl membandwidth report
  cmd/katalyst-agent/app/options/sysadvisor/metric-emitter/metric_emitter_plugin.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/node/node_test.go
  pkg/agent/sysadvisor/plugin/metric-emitter/syncer/pod/pod.go
  pkg/config/agent/sysadvisor/metric-emitter/metric_emitter_plugin.go
  pkg/consts/common.go
  pkg/consts/metric.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner_calculate.go
  pkg/metaserver/agent/metric/provisioner/malachite/provisioner_test.go
  pkg/metaserver/agent/metric/provisioner/malachite/types/cgroupv1.go
  pkg/metaserver/agent/metric/provisioner/malachite/types/cgroupv2.go
  pkg/metaserver/agent/metric/provisioner/malachite/types/common.go
  pkg/metaserver/agent/metric/provisioner/malachite/types/system.go
Labels: workflow/need-review

#869 feat(eviction): add CNR taint reporting support
  pkg/agent/evictionmanager/conditions.go
  pkg/agent/evictionmanager/conditions_test.go
  pkg/agent/evictionmanager/manager.go
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter.go
  pkg/agent/resourcemanager/reporter/cnr/cnrreporter_test.go
  pkg/client/control/reporter.go
  pkg/client/control/reporter_test.go
  pkg/controller/lifecycle/agent-healthz/handler/handler_generic.go
  pkg/util/cnr.go
  pkg/util/cnr_test.go
Labels: workflow/need-review

#879 fix(cpu/dynamicpolicy): skip zero cpuset or cpu request in metrics
  pkg/agent/qrm-plugins/cpu/dynamicpolicy/policy_async_handler.go
Labels: workflow/need-review
